### ISSUE TITLE
Pycbc's read-data-from-server functionality doesn't work for remote servers

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#1181]
Trying to use PyCBC's strain module with a *remote* datafind server (ie. if I set LIGO_DATAFIND_SERVER to a remote server) fails. I think we need more options to say that I want gsiftp urls back and then the code should know what to do with that.

```
XLAL Error - XLALHeapSort (../../../../lal/src/utilities/HeapSort.c:53): Invalid pointer
XLAL Error - XLALFrStreamCacheOpen (../../../lalframe/src/LALFrStream.c:225): Internal function call failed: Invalid pointer
Traceback (most recent call last):
  File "/home/spxiwh/lscsoft_git/executables_pycbc_masternew/bin/pycbc_single_template", line 200, in <module>
    gwstrain = strain.from_cli(opt, pycbc.DYN_RANGE_FAC)
  File "/home/spxiwh/lscsoft_git/executables_pycbc_masternew/lib/python2.7/site-packages/pycbc/strain.py", line 221, in from_cli
    end_time=opt.gps_end_time+opt.pad_data)
  File "/home/spxiwh/lscsoft_git/executables_pycbc_masternew/lib/python2.7/site-packages/pycbc/frame.py", line 329, in query_and_read_frame
    end_time=end_time)
  File "/home/spxiwh/lscsoft_git/executables_pycbc_masternew/lib/python2.7/site-packages/pycbc/frame.py", line 155, in read_frame
    stream = lalframe.FrStreamCacheOpen(cum_cache)
RuntimeError: Internal function call failed: Invalid pointer
```

**Comment by duncan-brown** [comment]
Make a DAX with one job? 🎱

**Comment by ahnitz** [comment]
I would assume this is something that you'd want to be handled by the function directly, i.e. so it works to run by hand as well.

**Comment by spxiwh** [comment]
A specific use-case where this would be useful is if someone wants to run a small test of pycbc_inspiral (or any other pycbc code) on a laptop/workstation using actual data. Being able to pull data, at run-time, would be a useful feature (and I think most of the stuff to do this is in place, it just needs hooking up).

**Comment by duncan-brown** [comment]
@spxiwh Is the use case on an LDG cluster or on your laptop? The ``/cvmfs`` access to frames is really nice for this. If you get ``file:///cvmfs/`` paths back from a datafind server and have CVMFS installed on your machine you can ``fopen()`` the paths and CVMFS will fetch them for you. That's how we have all the data on sugar.

**Comment by ahnitz** [comment]
@spxiwh I think that makes a lot of sense. I know that I've personally wanted that at times. Would be especially useful with things like the single template code, where I just want to make a quick plot. I can see how this would be nice for new people as well.

**Comment by duncan-brown** [comment]
@spxiwh @ahnitz you guys should really look at the CVMFS stuff. They have solved this problem for us so we don't need to code it:
```
[dbrown@sugwg-osg ~]$ ls /cvmfs/ligo.osgstorage.org/frames
ER10  ER8  O1  S6
```
It's trivial to install on an SL*/Ubuntu box. There's a Mac OS X image (although Brian needs to get the X509 cert stuff in there).

To install see https://twiki.grid.iu.edu/bin/view/Documentation/Release3/InstallCvmfs

**Comment by duncan-brown** [comment]
Here's the ROM data on my Mac, for example, pulled via CVMFS. I never installed this locally:
```
[dbrown@seaview ~]$ md5 /cvmfs/oasis.opensciencegrid.org/ligo/pipeline/pycbc/pycbc/ROM/lal-data/lalsimulation/SEOBNRv2ChirpTimeSS.dat
MD5 (/cvmfs/oasis.opensciencegrid.org/ligo/pipeline/pycbc/pycbc/ROM/lal-data/lalsimulation/SEOBNRv2ChirpTimeSS.dat) = 7b7dbadacc3f565fb2c8e6971df2ab74
```

**Comment by spxiwh** [comment]
I don't think the CVMFS stuff (which I agree is useful) has too much bearing on this pull request. We *already* have a system for distributing data: gsiscp and gw_data_find. Our codes already call into this. The request here is simply to close the loop on this and allow the strain module to understand what to do if a remote datafind server is in use and the frames returned are gsiftp locations, not local paths.

CVMFS might mean that this isn't the preferred way to do this in the future, but this hasn't been demonstrated with gw_data_find, and there are probably a bunch more i's to dot and t's to cross yet.

**Comment by duncan-brown** [comment]
And for Mac users, the install instructions are:

 * Install the FUSE package https://github.com/osxfuse/osxfuse/releases
 * Install the CVMFS package from http://cernvm.cern.ch/portal/filesystem/downloads

Then as root, create a file ``/etc/cvmfs/default.local`` that contains
```
CVMFS_REPOSITORIES="`echo $((echo oasis.opensciencegrid.org;echo cms.cern.ch;ls /cvmfs)|sort -u)|tr ' ' ,`"
CVMFS_QUOTA_LIMIT=20000
CVMFS_HTTP_PROXY=DIRECT
```
and then
```
mkdir /cvmfs/oasis.opensciencegrid.org
mount -t cvmfs oasis.opensciencegrid.org /cvmfs/oasis.opensciencegrid.org
```

**Comment by duncan-brown** [comment]
@spxiwh that's not true. It's working now and working well on sugar.
```
[dbrown@sugwg-osg ~]$ gw_data_find --file H-H1_HOFT_C02-1134456832-4096.gwf 
gsiftp://sugwg-osg.phy.syr.edu:15000/cvmfs/oasis.opensciencegrid.org/ligo/frames/O1/H1_HOFT_C02/H/1134/H-H1_HOFT_C02-1134456832-4096.gwf
file://localhost/cvmfs/oasis.opensciencegrid.org/ligo/frames/O1/H1_HOFT_C02/H/1134/H-H1_HOFT_C02-1134456832-4096.gwf
```

**Comment by duncan-brown** [comment]
Plus it has the advantage that it will *cache* the data you transfer (up to an admin specified cache size), so if you run the same program twice on the same data in short order, it won't re-transfer the data.

OK, I'll stop with the commercial now...

**Comment by GarethCabournDavies** [comment]
@spxiwh can this be closed?

**Comment by spxiwh** [comment]
Yes, this functionality (CVMFS, gsiftp and now OSDF) is all implemented.
