### ISSUE TITLE
The start script should capture the full submission environment

### ISSUE THREAD

**Issue by duncan-brown** [gwastro/pycbc#1281]
It would be nice if the ``./start`` script could capture the full submission environment so that the user doesn't have to remember what environment scripts they sources when resuming a workflow.

**Comment by ahnitz** [comment]
@duncan-brown I assume you mean the ./start script? The only thing I can think of is to export your environment to a file when you call pegasus submit dax, and then source it in the script. That would also be nice so you can see your submit environment later too for debugging.

**Comment by duncan-brown** [comment]
@ahnitz yes, that's what I was intending with that useful side-effect.

**Comment by ahnitz** [comment]
I think this is outdated enough that it is no longer being tracked. Please re-open if still needed.
