### ISSUE TITLE
Adding text/comments to html pages

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#1398]
It would be nice to be able to add short blocks of text/comments or even raw html to the html result pages. For example on the page here:

https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O2/analyses/O2_chunk3/prelim_analyses/C00_ODC_MASTER/run7a/5._injections/5.02_followup_of_missed_BNSSTT2_INJ/

It would be nice to add in the white box, just before A1, a note stating that we are defining "missed" to mean anything with IFAR < 100 yr. This information is known when putting together the followup page, but is not know when choosing the sub-directory name that the minifollowup will be run in ... So I cannot add it in the sub-section title.

**Comment by ahnitz** [comment]
@spxiwh It could be made easier to do this, but it can already be done by simply writing that string or html or whatever to a file and including the workflow.core.File handle to that file in your layout. The webpages already know to include content with a .html extension. In fact it is how that parameter table is made to begin with. Are you just asking for a helper function here that does the following ?  

```
file_handle = write_text("LOTS OF TEXT", output_dir=output_dir)
```

**Comment by ahnitz** [comment]
I believe this is not handled.
