### ISSUE TITLE
A workflow-supplied argument can also be given in the .ini file

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#1418]
Some workflow generators control job-specific arguments (like times or input files). These arguments are not expected to be given in the ini file. However, one *can* give such options in the ini file, which will result in the option being specified *twice* to a job.

The code should raise an error if the workflow generator tries to add an option that is already present in the ini file. Currently this issue will not be addressed as this is being used as a "feature" for at least one code in production. So not to break things I'll either fix this after that is resolved, or at the end of O2.

**Comment by GarethCabournDavies** [comment]
@spxiwh did you fix this after O2?

**Comment by spxiwh** [comment]
Not sure! Try adding `--gps-start-time` into the `[inspiral]` section of a config file, and see what happens!

**Comment by GarethCabournDavies** [comment]
Still happens.

My initial idea is to supply a list of command line arguments to the executable which will be set in the workflow, and cause errors on them if they are supplied in the command line. e.g. :
 - `self.workflow_generated_options` is added to Executable
 - `self.workflow_generated_options=['gps-start-time' ...]` is set for each executable as applicable
 - check `if opt in self.workflow_generated_options` in `_add_ini_opts(` (similar to time_dependent_options), and cuase an error if it is

and then

**Comment by GarethCabournDavies** [comment]
Completed in #4773
