### ISSUE TITLE
Make average PSD in coinc search workflow

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#1421]
As we need an averaged PSD to check the template bank for each chunk it makes sense to have that  produced automatically. I think the easiest thing is to add `pycbc_average_psd` to `pycbc_coinc_search_workflow`.

**Comment by ahnitz** [comment]
@spxiwh Is this still an issue?

**Comment by spxiwh** [comment]
It would be useful to have, but as it hasn't happened in over 4 years, we may as well close this.
