### ISSUE TITLE
Requests for PyCBC Inference Documentation

### ISSUE THREAD

**Issue by cmbiwer** [gwastro/pycbc#1431]
Particularly @stevereyes01 please look at the documentation and if something isn't clear please make suggestions.

Also @cdcapano if there's things you think need to be updated please add them here.

Right now, I still need to update the workflow documentation.

**Comment by stevereyes01** [comment]
Will do. Thanks.

**Comment by duncan-brown** [comment]
@stevereyes01 any update on this?

**Comment by stevereyes01** [comment]
I haven't run the examples in the documentation (http://ligo-cbc.github.io/pycbc/latest/html/inference.html) yet (I'll do that now).

Having example plots of the posteriors though in the last section would probably help the readability of the entire document though.

**Comment by stevereyes01** [comment]
Chris, can you add more explanation to the section : **Plotting a thinned chain of samples**

What does it mean to look at a thinned chain of samples?

What should a user be looking for when they decide to look at the posteriors after X samples vs after X+1 samples and so on?

What are some ways of checking that we've done enough samples such that "burn-in" has been accomplished? How do we know that the serial-correlation between the initial input of the sampling algorithm and the final posteriors are weak enough to trust the posteriors? It sounds like you have already thought about this problem a lot, so hopefully we can include a few basic tests in the documentation for users. If there's still more work to be done on coding up correlation tests maybe we can take some time to divide up the work?

I guess it would be nice to see this paragraph expanded out for those of us who don't know a lot about using MCMC's for parameter estimation:
```
By default the plotting executables will plot samples beginning at the end of the burn in. If the burn-in was skipped, then it starts from the first sample. It will then use a sample every autocorrelation length along the chain. Examples how to plot a specific iteration or change how the thinning is performed is shown in the examples below.
```

**Comment by cmbiwer** [comment]
This can probably be closed as well. People have opened up other issues for their requests.
