### ISSUE TITLE
Weirdness in wiki-format loudest trigger files

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#1626]
Sometimes, parts of the loudest trigger files in wiki format are repeated:

https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis11-full1/3._single_triggers/3.07_H1_loudest_noncoinc_time/H1FULL_DATA_noncoincloudest_table.txt

**Comment by tjma12** [comment]
@titodalcanton I'll take a look at why it might be doing this. It's not making anything fall over, just spitting out extra lines sometimes?

**Comment by titodalcanton** [comment]
Yes it looks like it's just repeating the list, not dropping anything. However, other files have just the header repeated:

https://www.atlas.aei.uni-hannover.de/~tito/LSC/o2/o2-analysis11-full1/3._single_triggers/3.10_H1_loudest_all_time_duration_gt_1.0_sec/H1FULL_DATA_longdurloudest_table.txt

Maybe a list is being reused without being reinitialized, or something like that?

Also if you make a PR, can I propose rounding the numbers a bit, and to a fixed number of digits? E.g. GPS times and durations to milliseconds, SNRs and masses/spins to hundredths etc.

**Comment by titodalcanton** [comment]
BTW, this feature is a huge time saver, thanks!

**Comment by tjma12** [comment]
Do you know if any of the jobs responsible for those pages were retried while the workflow was running?

**Comment by titodalcanton** [comment]
Apparently my first link was repeated, but the second was not:

https://www.atlas.aei.uni-hannover.de/pegasus/u/tito/r/171/w/2/j/11315/ji/25521
https://www.atlas.aei.uni-hannover.de/pegasus/u/tito/r/171/w/2/j/9426/ji/23316

**Comment by ahnitz** [comment]
@titodalcanton Is this still relevant? If not, please close.

**Comment by titodalcanton** [comment]
Probably no longer relevant.
