### ISSUE TITLE
pycbc_inference_plot_prior tries to import tkinter

### ISSUE THREAD

**Issue by hkqcap** [gwastro/pycbc#1802]
When executing pycbc_inference_plot_prior on clusters, it tries to import tkinter because one of the modules corner tries to import matplotlib.pyplot, without specifying backend agg.

This problem can be readily solved by moving the matplotlib import statement and backend selection statement in front of the corner import statement.

**Comment by cdcapano** [comment]
@cmbiwer Can you take a look at this? Can the call to corner be replaced using a call to `create_multidim_plot`, as it is in `plot_posterior`? Then we could remove corner entirely from the dependencies.

**Comment by cmbiwer** [comment]
Switching to ``create_multidim_plot`` resolves this. Can be closed.
