### ISSUE TITLE
FFT caching can unexpectedly cause memory usage to grow

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#1879]
There's apparently some memory caching done in the fft module (at least when using fftw as the backend) that is based on the length of the time/frequency series that is passed to it. The problem with this is it can silently cause memory usage to grow when using `to_frequencyseries` or `to_timeseries` on multiple different arrays of different lengths. Here's a simple test to highlight the problem:
```
from pycbc.types import zeros, FrequencySeries, complex128

N = 128*2048
ntrials = 1000
print "running on fixed size"
for ii in range(ntrials):
    hp = FrequencySeries(zeros(N/2 + 1, dtype=complex128), delta_f=1./128)
    hp.to_timeseries()

print "running on decreasing size"
for ii in range(ntrials):
    hp = FrequencySeries(zeros(N/2 + 1, dtype=complex128), delta_f=1./128)
    hp.to_timeseries()
    N -= 2
```
While the first loop is running, the memory usage stays a constant ~50MB, as expected. While the second loop runs, however, the memory usage grows quickly, getting to be > 1GB by the end of the loop, even though the size of the frequency series is _decreasing_.

I'm not sure what the best fix for this is. I understand that the caching helps performance, but I don't think this silent caching is a good idea. I spent the last two days tracking down a memory issue in pycbc inference due to this. Perhaps instead of caching each new length, it would be better to just cache a single block of memory, that is updated whenever a longer FFT is requested. Alternatively, `to_timeseries` and `to_frequencyseries` could resize to the nearest power of 2 before calling `(i)fft`, to minimize the number of lengths that are cached.

**Comment by ahnitz** [comment]
Disabled by @josh-willis
