### ISSUE TITLE
Installation Instructions Point to Pegasus WMS python libraries with old PyOpenSSL

### ISSUE THREAD

**Issue by rpfisher** [gwastro/pycbc#1927]
In the file:

https://github.com/ligo-cbc/pycbc/blob/master/docs/install.rst

The Instructions point to a tarball for Pegasus WMS python libraries that uses an old PyOpenSSL version (0.13).  This is incompatible with the updated OpenSSL on the CIT cluster and elsewhere.

**Comment by spxiwh** [comment]
@rpfisher Is it known if newer versions of pegasus fix this?

**Comment by spxiwh** [comment]
Seems that the answer to that is "no". Even the development 4.9.0 release is referencing PyOpenSSL. Probably need to raise this one with Karan.

**Comment by spxiwh** [comment]
I think this is now solved, but I think we need to ask Karan to have pegasus WMS managed on pypi so that we can just pull the latest version rather than specific URLs.
