### ISSUE TITLE
workflow start script issue

### ISSUE THREAD

**Issue by tapaimarton** [gwastro/pycbc#1962]
After stopping a workflow I was unable to restart it, there was a problem with the proxy issue, 

the bug is in

if [ -f /tmp/x509up_u`id -u` ] ; then
  unset X509_USER_PROXY
else
  if [ ! -z ${X509_USER_PROXY} ] ; then
    if [ -f ${X509_USER_PROXY} ] ; then
      cp -a ${X509_USER_PROXY} /tmp/x509up_u`id -u`
    fi
  fi
  unset X509_USER_PROXY
fi

**Comment by spxiwh** [comment]
Don't believe this is still an issue. Re-open if it is.
