### ISSUE TITLE
Starting kombine from a samples file doesn't respect continuity

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#1966]
As noted in PR #1961, if you start `pycbc_inference` from a samples file, it does not pick up as if it had run continuously when using kombine as the sampler. For example, [here](https://www.atlas.aei.uni-hannover.de/%7Ecdcapano/public_scratch/pycbc_prs/1961/kombine/posterior_iter20-0-20.png) is the 20th iteration from a run on a test 2D normal distribution. Compare to [this plot](https://www.atlas.aei.uni-hannover.de/%7Ecdcapano/public_scratch/pycbc_prs/1961/kombine/posterior_iter20-10-20.png), which also shows the 20th iteration, but done in two steps: first as a 10 iteration run, then as a second 10 iteration run, using the first run as input.

Since this works with emcee, I don't think it's due to the initial starting positions nor setting the state of numpy's random generator (unless kombine uses it's own generator under the hood?). That leaves the kde not being set correctly as the culprit. But since this apparently worked earlier, I'm not sure what changed that caused it to break.

**Comment by cmbiwer** [comment]
This can probably be closed now.
