### ISSUE TITLE
Add a workflow generator for parameter estimation PP tests

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#1970]
What the subject says.

**Comment by cmbiwer** [comment]
This will probably be a couple PRs. Something like:
- [ ] Add ``pycbc_inspinj`` executable that generates a population of signals from a ``pycbc_inference``-type ini file
- [ ] Add ``pycbc_inference_plot_recovery`` that plots recovery vs injected and option for PP-like plot
- [ ] Add ``pycbc_inference_validation_workflow`` that runs a bunch of inference jobs and then some post-processing step to generate some plots

**Comment by cdcapano** [comment]
@cmbiwer Aside from the workflow generator itself, I'm not sure if we need additional plotting scripts written for this or not. I don't know what you already have written. If we do need additional scripts, please feel free to create an issue for it and assign it to someone. I'd prefer it if you just focused on tying it all together in a workflow.

**Comment by cmbiwer** [comment]
@cdcapano Think we typed at same time but I have these scripts. But to avoid a >>1000 PR, I think I'll add the plotting/injection scripts that will be in the workflow separately. Then one PR to add then all into a workflow at the end.

**Comment by cdcapano** [comment]
@cmbiwer With respect to `pycbc_inspinj`, we already have that. See [pycbc_create_injections](https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_create_injections).

**Comment by cdcapano** [comment]
Yeah, it would be best to break this up into multiple PRs.

**Comment by cmbiwer** [comment]
> @cmbiwer With respect to pycbc_inspinj, we already have that. See pycbc_create_injections.

Ah okay, check!

**Comment by cmbiwer** [comment]
This was completed awhile ago. Closing.
