### ISSUE TITLE
Compare pycbc inference to LALInference on some injections

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#1973]
What the subject says. For the pycbc inference paper we're going to run LALInference on a subset of the injections from the PP tests. To complete we need:
* [ ] An injection set (depends on the PP workflow being completed)
 * [ ] LALInference runs on this set. Assigning this to @vivenr

**Comment by cmbiwer** [comment]
@cdcapano Should we close this as well?

**Comment by cdcapano** [comment]
Yeah, this was created for the pycbc inference paper project, but we decided not to do this anyway.
