### ISSUE TITLE
Figure out class inheritance for samplers

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#1982]
This is just a scratch space to discuss how best to organize the sampler classes' inheritance and attributes. Right now we have `BaseSampler`, `BaseMCMCSampler`, and then the kombine, emcee, emcee_pt, and (soon) mcmc samplers. We'll probably want to rearrange this a bit --- or at least move some attributes around --- to best incorporate all samplers, as well as add some base support for nested samplers. We should discuss this at the PE f2f.

**Comment by vivienr** [comment]
I'm adding the blackboard picture from the PE F2F:

![img_20171201_174219](https://user-images.githubusercontent.com/1928709/33652395-90ffe19c-da69-11e7-9beb-0038a5f8601d.jpg)

**Comment by cdcapano** [comment]
Here's my notes from our meeting:
```
Base sampler attributes:

 * log prior
 * log likelihood
 * evidence
 * from_config
 * run: all checkpointing, calculations of evidence, etc. should be done inside the run method. This will be a NotImplementedError at the base level.
 * a write (meta)data
 * a read (meta)data
 * a write standard output method

To do: add function to LikelihoodEvaluator to evaluate from structured array

BaseMCMC
 * iterations
 * implement a set_p0
```

**Comment by cmbiwer** [comment]
@cdcapano Can this be closed?

**Comment by cdcapano** [comment]
Yup
