### ISSUE TITLE
glue.datafind doesn't use M2Crypto any more, rethink function-level import

### ISSUE THREAD

**Issue by duncanmmacleod** [gwastro/pycbc#2015]
https://github.com/ligo-cbc/pycbc/blob/9e057e1cf9083a0ea6a5593ae4cecf420d343a7d/pycbc/frame/frame.py#L233-L235

As of 1.56, `glue.datafind` uses `pyOpenSSL`, rather than `M2Crypto`, for X509 validation, so a function-level import might be unnecessary (not sure about pycbc dependence on pyOpenSSL).

Sorry if this is spam, I saw the comment and thought I would mention the change.

**Comment by spxiwh** [comment]
Just to check @duncanmmacleod, this is in the version released in pypi, right? I'm working on the `pycbc_glue` > `glue` transition now and can fix this in the process.

**Comment by duncanmmacleod** [comment]
@spxiwh, yes, see [`glue 1.56.0`](https://pypi.python.org/pypi/lscsoft-glue/1.56.0). For completeness, the dependency specification should be

```
lscsoft-glue >= 1.56.0
```

**Comment by spxiwh** [comment]
This has been resolved for a while now.
