### ISSUE TITLE
install doc paths self-inconsistent?

### ISSUE THREAD

**Issue by couvares** [gwastro/pycbc#2054]
In install.rst, isn't the path in this statement: 

> Next, you need to choose a directory name where you'd like to make your virtual environment, and then make it. In this example, we use ${HOME}/pycbc-dev but this can be changed to any path that you you have write access to, except for ${HOME}/.local as that will cause conflicts with pip.

...in conflict with the path in this statement just two paragraphs later?

> You first set up a new virtual environment. A virtual environment is defined by a directory path that will hold the contents of the virtual environment. In this example, we chose ~/src/pycbc although you can change this to whatever you like by changing the command below.

Specifically, we first tell the user we will use ${HOME}/pycbc-dev, then we say we will use ~/src/pycbc (and then the following instructions proceed to use the latter path, ~/src/pycbc).

We ought to make this consistent.  It seems to me the former path is a better choice, at least given the conventions I am familiar with for checking out source repos into ~/src, making that a poor choice for a virtualenv.  But maybe I'm missing something.

I'm happy to edit the docs to use ${HOME}/pycbc-dev (or any other PATH people prefer as a default suggestion), but I wanted to check first to make sure I'm not confused.

**Comment by ahnitz** [comment]
The instructions now don't contain these statements
