### ISSUE TITLE
Bank generation workflow does not save version info

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2058]
(at least in a clear way).

**Comment by GarethCabournDavies** [comment]
This was not the intention of that work, but could be solved by #4768

**Comment by spxiwh** [comment]
@GarethCabournDavies It should run the new pycbc_page_versioning, or whatever it's called, like other workflows do.

**Comment by GarethCabournDavies** [comment]
Ugh, I missed that it is the *workflow* discussed here, not the bank itself
