### ISSUE TITLE
Minifollowups problem, "Condor DagMan doesn't allow . in job names"

### ISSUE THREAD

**Issue by stevereyes01** [gwastro/pycbc#2114]
I'm currently getting bitten by a bug similar to this https://jira.isi.edu/browse/PM-1222 and https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=5966

The error message I'm seeing is in the MiniFollowup Dags when I try running a `pycbc_make_coinc_search_workflow` in the dag.dagman.out file:
```
04/03/18 15:11:19 ERROR: H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dag (line 10): JobName create_dir_H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dax_0_local contains one or more illegal characters ('+', '.')
```
The relevant line in the dag is:
```
JOB create_dir_H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dax_0_local ./create_dir_H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dax_0_local.sub
```
The dag contains hundreds of calls to shell scripts and sub files using similar `./` or `.//./` syntaxes. As far as I know, all I think that needs to be changed is to remove the `.`'s in JOB names, but I'm not sure how to prevent the pegasus workflow from doing this automatically.

Looking back at an older run (~August 2017) that I did, I notice that this behavior in the minifollowup dags didn't seem to be a problem. So it seems related to a more recent release in HTCondor. Going back to some older files (~July 2015) I notice that these `./` and `.//./`'s aren't present in JOB names.

I'm going to tag @couvares to help me maybe understand what this error is about. Maybe somebody else can help me patch this behavior.

**Comment by stevereyes01** [comment]
Manually removing `./` from the dag JOB names (i.e. `./create_dir_H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dax_0_local.sub --> create_dir_H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dax_0_local.sub`) doesn't seem to have fixed the problem I'm having. So I'm stuck.

**Comment by couvares** [comment]
I think it's the "...300000.dax..." substring in the job name, not just the ./ prefix.  You still have a '.' in there...

**Comment by stevereyes01** [comment]
@ahnitz Should I go file this in Pegasus (https://jira.isi.edu/secure/Dashboard.jspa) and close the issue here?

**Comment by ahnitz** [comment]
@stevereyes01 Feel free to leave this open and crosslink, since it does affect us.

**Comment by duncan-brown** [comment]
I agree with @ahnitz that this is a pegasus issue. PyCBC has no control over the "." in these job names. The job that Steven cites is one created by Pegasus that doesn't exist in the PyCBC workflow. I think Pegasus needs to replace "." with some other character when it writes the DAX if this character is now forbidden by Condor.

**Comment by duncan-brown** [comment]
@vahi in addition to fixing this, it might also be good for pegasus to do a regexp sub on what it constructs from `<job id="ID0000001" name="segments_from_cats-H1L1_ID0">` just in case the user puts `.` or `+` in there.

**Comment by couvares** [comment]
Karan writes, in email:

> The . is in  in the generated DAX. Pegasus does not add it itself.
> In either the namespace, name or version attributes for the job element in the DAX

(Just trying to keep this thread comprehensible...)

**Comment by spxiwh** [comment]
Can someone point to something that is "wrong" in a dax file produced by pycbc.workflow? At the moment this us very unclear to follow!

**Comment by vahi** [comment]
@duncan-brown reply captures it
Hi Alex,

The issue is that PyCBC is creating an entry in a dax for a sub-dax that looks like this:

       <dax id="ID0021936" file="H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1186624818-687900.dax">
               <argument>--basename H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1186624818-687900 -Dpegasus.dir.storage.mapper.replica.file=H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1186624818-687900.dax.map -Dpegasus.dir.storage.mapper.replica=File --output-site local --cleanup inplace --cluster label,horizontal -vvv --cache /home/dbrown/projects/aligo/o2/analysis-21/o2-c00-analysis-21-v1.7.9-vdf-5c09540-auto-dch-gates/output/_reuse.cache</argument>
               <uses name="H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1186624818-687900.dax.map" link="input"/>
       </dax>

So it's not a job name, but the dax name. Pegasus is taking that filename and prepending createdir_ and _0_local to make the dagman job name. I suppose that Pegasus could say "users cannot give DAX filenames that contain . or +" but I think it would be easier for Pegasus to just silently enforce this.

and I agree we will fix it in Pegasus for a 4.8.2 release
https://jira.isi.edu/browse/PM-1262

**Comment by vahi** [comment]
Actually, I am a bit confused myself because i crosschecked in our test cases, and it is not happening what we see here.

For example here is the DAX for a hierarchal workflow being used

-bash-4.2$ cat outer.dax 
<?xml version="1.0" encoding="UTF-8"?>



<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.6.xsd" version="3.6" name="local-hierarchy">
	<job id="ID0000001" namespace="blackdiamond" name="generate">
		<argument>/usr inner.dax</argument>
		<uses name="inner.dax" link="output" transfer="true"/>
	</job>

	<dax id="ID0000002" file="inner.dax">
		<argument>--conf dax1.properties --output-site local -vvv --basename inner</argument>
		<uses name="dax1.rc" link="input"/>
		<uses name="dax1.properties" link="input"/>
		<uses name="dax1.sites.xml" link="input"/>
		<uses name="dax1.tc.text" link="input"/>
	</dax>
	<dax id="ID0000003" file="inner2.dax">
		<argument>--output-site local -vvv</argument>
	</dax>
	<job id="ID0000004" namespace="level2" name="sleep">
		<argument>5</argument>
	</job>
	<child ref="ID0000002">
		<parent ref="ID0000001"/>
	</child>
	<child ref="ID0000003">
		<parent ref="ID0000002"/>
	</child>
	<child ref="ID0000004">
		<parent ref="ID0000003"/>
	</child>
</adag>
-bash-4.2$ 



-bash-4.2$ condor_version
$CondorVersion: 8.6.10 Mar 12 2018 BuildID: 435200 $
$CondorPlatform: x86_64_RedHat7 $

We have a .dax in the filename
	<dax id="ID0000002" file="inner.dax">

-bash-4.2$ find . -name "create*in"
./00/00/create_dir_local-hierarchy_0_local.in
./00/00/inner.000/00/00/create_dir_diamond_0_local.in
./00/00/inner_ID0000003.000/00/00/create_dir_inner_0_local.in

What is the pegasus version being used? 
Also can you point me to a submit directory on syracuse for me to take a closer look

Thanks

**Comment by vahi** [comment]
@stevereyes01 can you point me to your failed runs.

**Comment by stevereyes01** [comment]
Hey Karan,

I'm on the sugwg-condor.phy.syr.edu cluster. The relevant directory would be `/home/steven.reyes/projects/astro/rough_draft_search_O1/attempt1/small_analysis_attempt_reuse_losc2/output/submitdir/work/O1_sub_analysis1_test_new_exec-main_ID0000001/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000` where the `H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dag` and `H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dag.dagman.out` were what I was looking at.

`H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051217-300000.dag.bak` is what the dag looked like before I started playing around with the dag file (like removing the ./ in the dag) to see if anything would work. (The behavior of the failure didn't seem to change at all though).

Please let me know if you need more information.

**Comment by vahi** [comment]
the source of the error is from the adag element, where the name of the adag is used to construct name for the create dir and cleanup jobs.  will push out a fix later today

?xml version="1.0" encoding="UTF-8"?>



<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.6.xsd" version="3.6" name="H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1126051
217-300000.dax">

**Comment by duncan-brown** [comment]
So we could fix this in PyCBC by stripping `.dax` off from the `adag` name as well.

**Comment by vahi** [comment]
yes that is correct. i have fixed it in Pegasus also. Right now our tests are currently running.
Once they are successful can point you to a build.

**Comment by vahi** [comment]
our tests were green.
you can pick up a new version from https://download.pegasus.isi.edu/pegasus/4.8.2dev/

**Comment by stevereyes01** [comment]
Thanks Karan! I'll test this out (most likely) on Monday depending on when Duncan downloads this on to our cluster.

**Comment by stevereyes01** [comment]
I should be able to close this issue later today. One of the minifollowup dags in my workflow completed, but some of the others did not succeed because I made a configuration error. Sorry. Will update later tonight. Thanks.

**Comment by stevereyes01** [comment]
I see minifollowups has succeeded and given no issues. Closing this for now. Thanks @vahi .
