### ISSUE TITLE
Method to generate FD waveform using TD approximant

### ISSUE THREAD

**Issue by duncanmmacleod** [gwastro/pycbc#2130]
It would be great to be able to generate a frequency-domain (FD) waveform using a time-domain (TD) approximant, using the public `get_fd_waveform` method, e.g.

```python
hp, hc = get_fd_waveform('SEOBNRv4')
```

In general it would be great for both `get_td_waveform` and `get_fd_waveform` to work with both domains transparently, with appropriate transforms hidden from the user.

**Comment by ahnitz** [comment]
This now works, so closing the issue.
