### ISSUE TITLE
ligolw header files not included in tarball from sdist for 1.10.0

### ISSUE THREAD

**Issue by duncanmmacleod** [gwastro/pycbc#2189]
The [1.10.0 release tarball](https://pypi.org/project/PyCBC/1.10.0/#files) doesn't include the `.h` files for `pycbc/ligolw`, so the build fails:

```
$ pip install pycbc
...
  creating build/temp.macosx-10.13-x86_64-2.7/pycbc/ligolw
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ipycbc/ligolw -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pycbc/ligolw/tokenizer.c -o build/temp.macosx-10.13-x86_64-2.7/pycbc/ligolw/tokenizer.o
  pycbc/ligolw/tokenizer.c:34:10: fatal error: 'tokenizer.h' file not found
  #include <tokenizer.h>
           ^~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
```

I think these need to be added to the `MANIFEST.in` file.

**Comment by spxiwh** [comment]
@duncanmmacleod Any way to test this without making a new release? (And I really hope we can move over to the proper ligolw soon ... Only I'm now not sure what the proper ligolw actually is!)

**Comment by ahnitz** [comment]
@duncanmmacleod @spxiwh I already fixed this and forced a new release.
