### ISSUE TITLE
Change of default behaviour in TimeSeries

### ISSUE THREAD

**Issue by Cyberface** [gwastro/pycbc#2190]
I think in commit eb9c1e8a55802170a14ba74277e7b1e6ddb7aa55 that some of the default functionality of `TimeSeries`  operations were altered.

Before eb9c1e8a55802170a14ba74277e7b1e6ddb7aa55 (e.g. in the previous commit to his 3ccc7aa2483f719efd81ed7f10204a19ed694b0d)
I could do the following

```
import pycbc
from pycbc.types import TimeSeries
import numpy as np
cplx = np.ones(10)*1.j
ts = TimeSeries(cplx, delta_t=1.)
out = np.real(ts * np.conjugate(ts))
print(out)
```

The output of this is

```
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```

Now if I use commit eb9c1e8a55802170a14ba74277e7b1e6ddb7aa55 the same piece of code outputs:

```
<bound method TimeSeries.real of <pycbc.types.timeseries.TimeSeries object at 0x7f14ed6bea50>>
```

I can get the code to work if I use the `.data` attribute of the TimeSeries i.e.

```
out = np.real(ts.data * np.conjugate(ts.data))
```

Is this the desired behaviour? Or is it a bug?
I don't understand the python magic that @ahnitz did in commit eb9c1e8a55802170a14ba74277e7b1e6ddb7aa55 :)

**Comment by spxiwh** [comment]
That actually smells like a numpy bug @ahnitz ?

**Comment by ahnitz** [comment]
@Cyberface This looks so far like a bug in numpy to me... 

I'll do some digging, but for your future reference, you can simply do.

```
out = (ts * ts.conj()).real()
```
None of the numpy functions are needed here.

**Comment by ahnitz** [comment]
Or the entire operation as 

```
out = ts.squared_norm()
```

**Comment by ahnitz** [comment]
Also, in general try to avoid using the '.data' attribute. If you find yourself needing too, we should probably add some additional functionality to the types.

**Comment by Cyberface** [comment]
OK thanks!

**Comment by ahnitz** [comment]
@Cyberface I've tracked it down to a numpy bug in how it is checking for the 'real' property (in our case a method). It's not so robust. What you get will be the result anytime numpy.real is called on a pycbc type. The difference is that most of the type our types will now play nicely with numpy and the intermediate operations all all resulting in pycbc types whereas before one of the operations was causing a slow conversion and it wasn't making it to the outer numpy.real call.

**Comment by ahnitz** [comment]
I'll try to think of a patch on our side, as numpy is not so quick to change.
