### ISSUE TITLE
pycbc_build_eah.sh needs a two files moving to albert.phys.uem.edu

### ISSUE THREAD

**Issue by duncan-brown** [gwastro/pycbc#2234]
https://github.com/gwastro/pycbc/pull/2233 required adding two new files to the EAH build script to exercise software injections as part of the bundle build:

 * https://raw.githubusercontent.com/duncan-brown/pycbc/bundle_fix/tools/einsteinathome/H1L1-SINGLE_TEMPLATE_BANK.xml
 * https://raw.githubusercontent.com/duncan-brown/pycbc/bundle_fix/tools/einsteinathome/HL-INJECTIONS.xml

@bema-ligo please can you add these to albert.phys.uwm.edu and create a pull request that:

 1. Deletes them from the PyCBC GitHub repo, and
 2. Updates the `pycbc_build_eah.sh` script with the location of the new files? Search for the three FIXME in the script and it should be pretty obvious what needs to be changed.

Thanks!

**Comment by bema-ligo** [comment]
PR filed.
