### ISSUE TITLE
"No module named ligo"

### ISSUE THREAD

**Issue by mgnoor** [gwastro/pycbc#2250]
I've been trying to step through the pycbc tutorial found at https://notebooks.azure.com/nitz/libraries/pycbc and I'm having a persisting issue where I'll run a provided block of code, and it errors, with the statement "ImportError: No module named ligo." I'm not sure whether this is a bug in the pycbc code, an issue with the azure notebook, or some other extraneous issue. Any help addressing this issue would be greatly appreciated.

**Comment by ahnitz** [comment]
@mgnoor Thanks for reporting this. If there is a larger traceback, can you please post it?

**Comment by ahnitz** [comment]
@mgnoor I was able to reproduce this, I'll take a look and get back to you.

**Comment by mgnoor** [comment]
<img width="1105" alt="screen shot 2018-07-16 at 2 09 57 pm" src="https://user-images.githubusercontent.com/40556034/42783822-fa4e225c-8901-11e8-9e83-3376aa91a683.png">
I attached one example. It looks like every instance I found occurred during a call to merger.strain().

**Comment by ahnitz** [comment]
@mgnoor I've tracked the problem into a bug in the upstream lalsuite package that just came out. I'm going to pin the version in the tutorials for now and file a bug report upstream. You should be able to get this to work if you replace the pip install commands at the top with the following (I'm going to do so in the official tutorials repo myself in a moment). 
```
import sys
!{sys.executable} -m pip install lalsuite=='6.48.1.dev20180620' pycbc
```

**Comment by ahnitz** [comment]
@mgnoor If you get the chance, let me know if that resolves this issue for you.

**Comment by mgnoor** [comment]
Yes, this worked perfectly. Thank you for the help.
