### ISSUE TITLE
Warning with current pycbc master

### ISSUE THREAD

**Issue by Cyberface** [gwastro/pycbc#2265]
If I do a fresh pip install of pycbc and then import pycbc I get the following:

anyone else?

```
(ptest) [Sebastians-MacBook-Pro 10:25 ~]$ python
Python 2.7.14 (default, Mar 10 2018, 00:01:11)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycbc
/Users/sebastian/ptest/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/Users/sebastian/ptest/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/Users/sebastian/ptest/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
```

**Comment by spxiwh** [comment]
This probably wouldn't be a PyCBC bug, but maybe a pip bug.

What I think has happened is upgrading/installing pycbc has caused an upgraded numpy to be installed. However, h5py was either not recompiled against the new numpy or was compiled first and then compiled against the system numpy (which it shouldn't have been able to see).

You should try forcing a reinstall of `h5py`

```
pip install --upgrade h5py
```

or some other command to force reinstall if you do have the latest version.

**Comment by Cyberface** [comment]
Yeah the problem comes from `import h5py`

I tried pip uninstall h5py, upgraded h5py upgraded pip.
Nothing works.

:(

**Comment by lauranuttall** [comment]
Yep I did an install from scratch yesterday and see the same thing. I'm guessing hdf5-1.8.12 isn't what we're wanting anymore?

**Comment by spxiwh** [comment]
Okay, reproduced, and I have a hunch about the cause, give me a minute.

**Comment by spxiwh** [comment]
Could someone try:

```
pip uninstall h5py
pip install --no-cache-dir --no-binary h5py h5py
```

This will force h5py to install from source, rather than pulling it's precompiled wheel, which is precompiled against an older numpy.

**Comment by spxiwh** [comment]
(You'll need to have a recent version of pip .... But then you probably won't see this error at all with older version!)

**Comment by Cyberface** [comment]
worked for me!

**Comment by lauranuttall** [comment]
yep seems to have worked for me

**Comment by Cyberface** [comment]
It seems that GWin has a similar problem but this time with scipy.
I found that your `--no-binary` trick works there too.

This is annoying - should we make this so that it is automatically done when pip installing or just add a note to the documentation for now?

**Comment by spxiwh** [comment]
I don't know how we can make this done automatically when installing?

There should be a way to tell the pip to install *everything* from source, which we could put in the docs .... But I don't understand why pip would do this? Surely `pip install numpy scipy` is a pretty common thing to do!?

**Comment by spxiwh** [comment]
I guess the "safe" way to install things with this new pip is:

```
pip install lalsuite
```

(that's a wheel itself so you have to enable binaries ... or just install from source) and then:

```
pip install --no-binary :all: pycbc
```

(which will probably take a lot longer than the wheels!)

**Comment by spxiwh** [comment]
I'm going to add @duncanmmacleod to this, as he's the python expert, this will affect GWin as much as PyCBC, and I don't know the best way to handle it!

**Comment by duncanmmacleod** [comment]
this also happens with scipy, for the record, and I think is related to the numpy-1.15.0 release, I can only presume that wheels on pypi aren't updated for numpy-1.15.0, but also don't mind living alongside it (except for the above warnings).

**Comment by ahnitz** [comment]
This issue is known to numpy. They silence the warnings for themself and so does matplotlib. See here. https://github.com/numpy/numpy/pull/432/commits/170ed4e33d6196d724dc18ddcd42311c291b4587?diff=split

Consequently, this may be added into pycbc in #2274

**Comment by Cyberface** [comment]
Is it just me or has this issue gone away now?

**Comment by ahnitz** [comment]
It should be on master anyway.
