### ISSUE TITLE
python3 problem

### ISSUE THREAD

**Issue by brettlv** [gwastro/pycbc#2273]
pycbc installed in python3 environment, but only the approximant "SEOBNRv2" can be used;
besides,i met trouble with highpass_fir,psd,and so on...

when can we use full function with python3?

**Comment by ahnitz** [comment]
Hi @brettlv. Python 3 is not officially supported yet. We are working on porting it to python 3 at the moment. For now, we recommend creating a python2 environment. Hopefully in a couple months python 3 support will be stabilized.
