### ISSUE TITLE
Feature request: add arg to get_td_waveform_from_fd

### ISSUE THREAD

**Issue by Cyberface** [gwastro/pycbc#2314]
I would like to add a new arg to the following function [get_td_waveform_from_fd](https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L573).

Sometimes if the estimate for the epoch is not good enough that the peak to not close enough to `t=0` then the current code will produce TD waveforms that have the end of the waveform wrapped around near the beginning of the time series.

I found that by increasing `rwrap` — which is hardcoded to 0.2 (units??) — was able to fix this problem. rwrap is [here](https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L607)

I think it would be good to add this as an arg, perhaps with a default value of 0.2?

If people think it's a good idea I will create a MR.

Cheers

**Comment by spxiwh** [comment]
That's 0.2 seconds .... How badly off are these waveforms in terms of epoch!?

(I don't see an issue with adding such a kwarg here, but waveforms off by this much are a problem!)

**Comment by Cyberface** [comment]
@spxiwh a preliminary check shows that in extreme parts of parameter space phenomHM currently has a error in the epoch of about 0.35s.

And yes, I'm trying to fix this :)

OK, I'll submit a MR
