### ISSUE TITLE
pycbc_submit_dax duplicate options

### ISSUE THREAD

**Issue by Cyberface** [gwastro/pycbc#2318]
Hi,

I think there is a bug in `pycbc_submit_dax`. The `-k` short form option appears twice.

Once here: https://github.com/gwastro/pycbc/blob/master/bin/pycbc_submit_dax#L200
and against here: https://github.com/gwastro/pycbc/blob/master/bin/pycbc_submit_dax#L206

**Comment by duncan-brown** [comment]
@Cyberface please can you submit a pull request to change the second use to `K`?
