### ISSUE TITLE
The options that validate the strain and psd arguments are commented out in pycbc_inference

### ISSUE THREAD

**Issue by duncan-brown** [gwastro/pycbc#2336]
While @cdcapano was walking people through `pycbc_inference`, we noticed that [line 148](https://github.com/gwastro/pycbc/blob/master/bin/inference/pycbc_inference#L148) and 
[line 150](https://github.com/gwastro/pycbc/blob/master/bin/inference/pycbc_inference#L150) disable the checks on the strain and PSD args.

Collin can't remember why these were commented out. This issue is to remind us to go back and check and see if they can simply be uncommented as is, or if uncommenting them breaks something.

**Comment by spxiwh** [comment]
Can this be a pull request with the same information?

**Comment by duncan-brown** [comment]
@spxiwh it's more complicated than just uncommenting them. We need to check it first and the functions may need changes.

**Comment by cdcapano** [comment]
Fixed by #3091
