### ISSUE TITLE
error while importing pycbc.noise module

### ISSUE THREAD

**Issue by FedericoMuciaccia** [gwastro/pycbc#2406]
if I try
`import pycbc.noise`
I got an error because the `gaussian` package cannot be found

the error disappear if in the file
`pycbc/pycbc/noise/__init__.py`
you change 
`from gaussian import noise_from_psd, noise_from_string, frequency_noise_from_psd`
into
`from pycbc.noise.gaussian import noise_from_psd, noise_from_string, frequency_noise_from_psd`

can you change it?

**Comment by ahnitz** [comment]
@FedericoMuciaccia I can't reproduce this error, but I can see you might get one if you have another package named 'gaussian'. This should be an explicit relative import. Thanks for catching that!

So it should be
```
from .gaussian import noise_from_psd, noise_from_string, frequency_noise_from_psd
```

Would you mind making a pull request to make this change? We'd be happy to accept your contribution to pycbc. Also, it's nice to publicly credit bug fixes from people.

**Comment by FedericoMuciaccia** [comment]
@ahnitz thanks for th proposal, but I'm not so good with Git and do all the clone-branch-merge for just the addition of a dot seems a little overkill :)
can you add it instead?

**Comment by ahnitz** [comment]
@FedericoMuciaccia Yep, will do.

**Comment by ahnitz** [comment]
@FedericoMuciaccia Change in place. Let me know if that works for you.https://github.com/gwastro/pycbc/commit/4d74dc90112d24bf0da3003056338c84a3af91f5

**Comment by FedericoMuciaccia** [comment]
@ahnitz now it works. thanks!
