### ISSUE TITLE
Make all waveform transforms explicit

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#2407]
Currently the generator module tries to automatically figure out what transforms are needed to go from the variable parameters to parameters understood by the waveform generator. In addition, we have the ability to explicitly specify what transforms to do in the config file. This mixture of silently applied transforms and explicit transforms is confusing (and caused 3 people to spend nearly an entire trying to debug an unexpected result). The proposal here is that the automatic function is removed, with all transforms being made explicit in the config file.

In addition, the `SphericalSpin1ToCartesianSpin1` and `SphericalSpin2ToCartesianSpin2` transforms are too specific to things called `spin1[...]` and `spin2[...]`. There should just be a single `SphericalToCartesian` transform that takes as input arguments the names of the spherical parameters to transform, along with the names of the output parameters it transforms to. That would make it even more clear what parameters were being transformed to what in the configuration file.

So, with these changes, the standard configuration file for spins would look something like:
```
[variable_params]
spin1_a =
spin1_aziumthal =
spin1_polar =

[prior-spin1_a]
name = uniform
min-spin1_a = 0
max-spin1_a = 0.99

[prior-spin1_azimuthal+spin1_polar]
name = uniform_solidangle
polar-angle = spin1_polar
azimuthal-angle = spin1_azimuthal

[waveform_transforms-spin1x+spin1y+spin1z]
name = spherical_to_cartesian
magnitude = spin1_a
polar = spin1_polar
azimuthal = spin1_azimuthal
output-x = spin1x
output-y = spin1y
output-z = spin1z
```
and similar for spin2.

**Comment by ahnitz** [comment]
This is largely done now.
