### ISSUE TITLE
RuntimeError: Oh no! You tried to use capabilities we haven't ported to python3 yet

### ISSUE THREAD

**Issue by lhm315** [gwastro/pycbc#2431]
Hello,
its my first time using gwpy trying to calculate the snr, I installed LALSuite and LALSimulation but when I call the matched_filter()  function the below error message pops up:
from pycbc.filter import matched_filter
snr = matched_filter(hp, zoom.to_pycbc(), psd=psd.to_pycbc(),
                     low_frequency_cutoff=15)
KeyError: <function correlate at 0x7fdf4dbe9d08>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luo/桌面/4 months ago/pycbc-snr/pycbc-snr.py", line 28, in <module>
    low_frequency_cutoff=15)
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1309, in matched_filter
    high_frequency_cutoff=high_frequency_cutoff, h_norm=sigmasq)
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter.py", line 1227, in matched_filter_core
    correlate(htilde[kmin:kmax], stilde[kmin:kmax], qtilde[kmin:kmax])
  File "<decorator-gen-160>", line 2, in correlate
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/scheme.py", line 187, in scheming_function
    return schemed_fn(*args, **kwds)
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/filter/matchedfilter_cpu.py", line 134, in correlate_inline
    libraries=omp_libs
  File "/home/luo/.local/lib/python3.6/site-packages/pycbc/weave.py", line 71, in inline
    raise RuntimeError("Oh no! You tried to use capabilities"
RuntimeError: Oh no! You tried to use capabilities we haven't ported to python3 yet
Could you please help me?

**Comment by spxiwh** [comment]
Hi @lhm315, unfortunately the error is correct. The `matched_filter` function in PyCBC uses the old `weave` module (formerly part of scipy) for optimization. This module was never ported to python 3, and never will be. To allow this to run in python3 we need to rewrite this, and a number of other functions, in Cython. We are working on this and hope to have most of these issues resolved within the timescale of 3-4 months.

Unfortunately, for now, you would need to use python2 to run this function while we work on supporting python3.

**Comment by ahnitz** [comment]
@lhm315 In the meantime, you might like the tutorials we've put together on how to use these kinds of functions. They run in interactive jupyter notebooks directly in your browser. See here. 

For microsoft azure (you'll need to make a free account)
https://notebooks.azure.com/nitz/projects/pycbc

Or if you prefer google. 
https://colab.research.google.com/github/gwastro/PyCBC-Tutorials/blob/master/tutorial/3_WaveformMatchedFilter.ipynb

**Comment by lhm315** [comment]
@spxiwh Thank you very much for your answer. I am installing gwpy in python2. It is obviously installed. After restarting the computer, re-import gwpy under python2. Will it show that there is no such module? Even opening jupyter under the terminal will not work?

**Comment by lhm315** [comment]
@ahnitz Since I am using a Linux system, I tried to open the jupyter using the command jupyter notebooks& under the terminal, but it did not open and an error popped up.

**Comment by lhm315** [comment]
>>> high = data.highpass(15)
/home/luo/opt/anaconda2/envs/gwpy/lib/python2.7/site-packages/astropy/units/quantity.py:1153: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = super(Quantity, self).__getitem__(key)
/home/luo/opt/anaconda2/envs/gwpy/lib/python2.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]

**Comment by ahnitz** [comment]
@lhm315 Please post again if you have any other questions we can help with. I'm closing this for now, and hopefully in a few months we can announce python3 support.
