### ISSUE TITLE
PyCBC catalog missing events

### ISSUE THREAD

**Issue by geoffrey4444** [gwastro/pycbc#2434]
~~~~
from pycbc import catalog
for name in catalog.Catalog():
  print name
~~~~

still outputs
~~~~
LVT151012
GW170608
GW150914
GW170814
GW170817
GW170104
GW151226
~~~~

Is it straightforward to update the catalog to include all of the GWs from GWTC-1? More generally, how will the catalog get updated in the future as LIGO/Virgo release more detections?

**Comment by ahnitz** [comment]
It's pretty straightforward. The thing I've been thinking about though is that since there are also multiple catalogs now, it should be possible to switch sources. In the meantime though, we can add in the additional events.

**Comment by geoffrey4444** [comment]
That would be great, adding in the additional events! Switching catalogs would also be nice. Thanks for the reply @ahnitz! I'm happy to test as soon as it's ready. :)

**Comment by ahnitz** [comment]
@geoffrey4444 Sorry for the very long delay here. I finally got around to addressing this. Hopefully, the pull request #2552 should address the issue.
