### ISSUE TITLE
Can't enter the official website of PyCBC? 

### ISSUE THREAD

**Issue by lhm315** [gwastro/pycbc#2436]
I would like to ask my computer has been connected to the network, why not enter the official website of PyCBC? http://pycbc.org this website can not open?

**Comment by ahnitz** [comment]
The link works for me. That's quite strange. What error are you getting?

**Comment by ahnitz** [comment]
BTW it should redirect you to the https encrypted site. https://pycbc.org/.

**Comment by ahnitz** [comment]
I have no problem opening that link either in either Chrome or Firefox. Out of curiosity are you located behind some firewall or proxy? The most likely answer is that somewhere along the line port 80 is being blocked.

**Comment by lhm315** [comment]
If  somewhere along the line port 80 is being blocked.what should I do?

**Comment by ahnitz** [comment]
I don't think I have a general answer for you. That's something you might have to work out with a local network admin if it is caused by an institution / company network. 

You might get some more information if you see what the error / diagnostic information from the browser is.

**Comment by lhm315** [comment]
This site is temporarily unavailable or too busy. Please try again in a few minutes.
If you can't load any webpages, check the network connection status of your computer.
If your computer or network is protected by a firewall or proxy server, verify that Firefox is authorized to access the network.
This is prompt message.
