### ISSUE TITLE
How should the code in the ini file run?

### ISSUE THREAD

**Issue by lhm315** [gwastro/pycbc#2444]
How should the code in the ini file run?

**Comment by lhm315** [comment]
[model]
name = test_normal

[sampler]
name = emcee
nwalkers = 5000
niterations = 100

[variable_params]
x =
y =

[prior-x]
name = uniform
min-x = -10
max-x = 10

[prior-y]
name = uniform
min-y = -10
max-y = 10
For example, the code in this file, I am running in the terminal, will pop up the following error
Command 'name' not found, did you mean:

  command 'mame' from snap mame (mame0201)
  command 'nam' from deb nam
  command 'nama' from deb nama
  command 'uname' from deb coreutils
  command 'nvme' from deb nvme-cli
  command 'named' from deb bind9
  command 'mame' from deb mame
  command 'lame' from deb lame
  command 'namei' from deb util-linux

See 'snap info <snapname>' for additional versions.

**Comment by ahnitz** [comment]
@lhm315 We have some documentation how to do this here. https://pycbc.org/pycbc/latest/html/inference.html#running-on-an-analytic-distribution

These files are meant to be fed to the pycbc_inference program to run. It's not exactly code, but really a configuration file for how the inference should be done.

**Comment by lhm315** [comment]
#!/bin/sh
pycbc_inference --verbose \
        --config-files normal2d.ini \
        --output-file normal2d.hdf \
        --nprocesses 2 \
        --seed 10 \
        --force
I understand the above configuration files, should I run the file code I sent above?

**Comment by lhm315** [comment]
2018-12-26 21:51:52,369 Using seed 10
2018-12-26 21:51:52,370 Running with CPU support: 1 threads
2018-12-26 21:51:52,428 Reading configuration file
Traceback (most recent call last):
  File "/home/luo/opt/anaconda2/bin/pycbc_inference", line 134, in <module>
    cp = option_utils.config_parser_from_cli(opts)
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/inference/option_utils.py", line 60, in config_parser_from_cli
    return WorkflowConfigParser(opts.config_files, overrides)
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/workflow/configuration.py", line 369, in __init__
    configFiles = [resolve_url(cFile) for cFile in configFiles]
  File "/home/luo/opt/anaconda2/lib/python2.7/site-packages/pycbc/workflow/configuration.py", line 192, in resolve_url
    raise ValueError(errmsg)
ValueError: Cannot open file normal2d.ini from URL normal2d.ini
When I run the above code, I get the above error.

**Comment by lhm315** [comment]
[prior-polarization]
; polarization prior
name = uniform_angle
In this command, the polarization angle is uniformly distributed, and we do not need to give a uniform distribution range? Or is the default between [0, 2pi]?
