### ISSUE TITLE
Convert NumPy Array to pycbc.types.timeseries.TimeSeries

### ISSUE THREAD

**Issue by arjung128** [gwastro/pycbc#2447]
I'd like to convert my NumPy array which represents a gravitational wave with 8192 time-steps into pycbc.types.timeseries.TimeSeries to be able to use the match function -- how can I go about doing this?

**Comment by micamu** [comment]
Assuming that you know what the time step (delta_t) and the start time (epoch) of the waveform is, you just need to do
```from pycbc.types import TimeSeries
gw_timeseries = TimeSeries(numpy_array), delta_t=time_step, epoch=start_time)```
with `numpy_array`your array
(if you skip the `epoch` option then it will just set gw_timeseries.start_time to 0)
