### ISSUE TITLE
Path on Docker example

### ISSUE THREAD

**Issue by alex-nielsen** [gwastro/pycbc#2457]
The line
>>> execfile("/home/pycbc/src/pycbc/examples/waveform/match_waveform.py")
is not working from Docker example on the main page of https://pycbc.org/

**Comment by duncan-brown** [comment]
Should be `/opt/pycbc`. I'll fix.

**Comment by ahnitz** [comment]
@duncan-brown Poke on this issue. I just got another email from somehow asking about this.

**Comment by duncan-brown** [comment]
@ahnitz do we want to simplify the Docker image while we're at it?

**Comment by ahnitz** [comment]
@duncan-brown Both would be nice to do and the path will likely change for that, so yeah same time make sense.

**Comment by GarethCabournDavies** [comment]
I dont think this is relevant any more / may have been fixed previously, so will close
