### ISSUE TITLE
1.13.2 much slower than 1.12.2

### ISSUE THREAD

**Issue by EnSlavingBlair** [gwastro/pycbc#2463]
Hi,

I had pycbc 1.12.2 on my laptop and 1.13.2 on my beefier desktop, and yet my desktop was running the same code ~50x slower than the laptop. A colleague and I narrowed it down to the detector.antenna_pattern function, and probably the change from lal to astropy within it. 

I changed my desktop pycbc to 1.12.2, the same as the laptop, and now it's running faster than the laptop as expected. 

Is there any major difference in the reliability of results between the two versions? I am doing statistics and need all the speed I can get, but I don't want to use something that's going to give me inferior results. 

Cheers!

**Comment by ahnitz** [comment]
@EnSlavingBlair Yes, it is likely the switch to using astropy. For most purposes, the accuracy, while better with the astropy version, won't be a noticeable problem. This is assuming you are not needing to track changes in the detector antenna pattern for long periods of time (weeks -> years) at high precision. If you are doing transient phenomena then you won't have a problem with the previous version. 

We'll leave this issue open to see if we can find a solution for your use case. Do you need to perform antenna pattern checks one at a time for example? One of the advantages of the new interface is that it can accept numpy array input. If you have many evaluations to do, and can do so all at once, the performance can be higher than the old implementation. If this isn't something that fits your use case, it would be good to know.

**Comment by ahnitz** [comment]
@EnSlavingBlair In your use case, are you using a fixed time? This case should be sped back up shortly.

**Comment by ahnitz** [comment]
@EnSlavingBlair I think should be now resolved on master. If you get the chance, can you let me know if this works for you?

**Comment by ahnitz** [comment]
@EnSlavingBlair I think this should be now fixed. Please do reopen this issue if you find that I am in error.
