### ISSUE TITLE
pycbc doesn't work if pycuda is installed

### ISSUE THREAD

**Issue by wsjyhaozi** [gwastro/pycbc#2482]
Hi,
Recently I'm trying to add CUDA support for pycbc. I followed the instructions in the documentation. But if I install pycuda, when importing any package from pycbc, an error will appear "Could not find library lal" and Python will quit automatically. For example, even runing "pycbc_inference -h" causes the error. However if I uninstall pycuda, pycbc works very well. 

I'm wondering if there is any conflict between pycbc and pycuda? 

My computer is mbp2018 and the system is High Sierra. I'm using an external GPU. The version of pycbc, CUDA and pycuda are the latest.

**Comment by ahnitz** [comment]
@josh-willis Any thoughts? You've been working on the cuda support most recently?

**Comment by ahnitz** [comment]
@wsjyhaozi At fist glance this seems odd. When you have pycuda installed, what happens if you just try to import lal from a python terminal manually? Can you report the result?

**Comment by wsjyhaozi** [comment]
@ahnitz If I import lal or pycbc no error message appears. But if I import a sub package like " import pycbc.inference" the error appears.

**Comment by josh-willis** [comment]
@ahnitz @wsjyhaozi I don't know if I would have anticipated your specific error, but there may be problems with using CUDA as recent as 10.0, if you do anything that might try to use an FFT (you might not be doing this yourself; it may be sufficient simply to import something that itself imports the FFT module in anticipation that it may need to do that).

Make sure you have the latest version of `sckit-cuda` (which I think is 0.5.2) and try  CUDA strictly less than 10.0 (I've only tested with CUDA 9.0 recently).

**Comment by wsjyhaozi** [comment]
@ahnitz @josh-willis I fixed the problem. It comes from pycbc.libutils.pkg_config. There was no "pkg-config" installed in my system. After I installed it, created a .pc file and added it to PKG_CONFIG_PATH, the problem was solved. 
Right now I met another error... When I run pycbc_inference, an error appeared "ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject". 
I googled it and they said upgrading numpy to 1.16.0 can solve it. However if I upgrade numpy to 1.16.0, I get "cannot import name _get_ndarray_c_version". And it seems only downgrading numpy can solve it...
Can you give me any suggestion?

**Comment by wsjyhaozi** [comment]
@ahnitz @josh-willis I tried numpy 1.14.1 and the problem was solved. Thank you very much for your help!
