### ISSUE TITLE
Add file names (and checksum?) to the attributes of hdf files

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#251]
Currently, STATMAP, TRIGGERMERGE, and HDFINJFIND files make references to other files without actually recording those files' names anywhere. For example, STATMAP files have 'template_id' in their foreground and background fields, which point to a template in a BANKHDF file, but the name/location of the bankhdf file is not stored anywhere in the file. Ditto 'trigger_idX' (which point to single detector ids) and TRIGGERMERGE files. Likewise, HDFINJFIND files will include an injection_id which points to an injection in an INJECTION xml file, but doesn't record which file. (These are particularly annoying, since there are multiple INJECTION files in a run, and the HDFINJFIND file names don't exactly match the INJECTION file name.) This means that if a user wants to do something with both coincident results and single-detector results, they just have to know which file goes with what. Also, if you want to write a program that uses information from multiple files, you have to have the user provide all the files on the command line, e.g., 'coinc-files STATMAP --bank-file BANKFILE', etc.

This also isn't very safe from a review stand point. There's no way to ensure that, for instance, the TRIGGERMERGE file that a STATMAP file used on creation is the same TRIGGERMERGE file currently sitting in the run directory.

The request is that the files on which each hdf file depends on get recorded in the attributes of that file, along with a checksum. In particular: STATMAP files record the BANKHDF, and TRIGGERMERGE files that they use. HDFINJFIND files record the BANKHDF, TRIGGERMERGE, INJECTION*xml, and STATMAP files. TRIGGERMERGE files record the BANKHDF file.

As I'm not too familiar with what codes generate each of these files, I'm just throwing this out there right now to see if anyone wants to take this on. If not, I'll come back to it and try to do it myself.

**Comment by duncan-brown** [comment]
This is probably more of a documentation issue for O1. Provenance across workflows is a bigger question.

**Comment by ahnitz** [comment]
Old, re-open if still relevant.
