### ISSUE TITLE
PyCBC Live occasionally uploads nonsensical candidates

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#2587]
It looks like we need more error checking. [This XML file](https://gracedb-playground.ligo.org/events/G12819/view/) has identically zero PSDs and identically NaN SNR time series at all detectors. I suspect this happened when the analysis had fallen behind and was stuck at the end of the low-latency frame buffer.

**Comment by ahnitz** [comment]
@titodalcanton Is this still happening?

**Comment by titodalcanton** [comment]
I have not checked systematically all uploads, but I have no evidence of this happening again in the last months. Closing.
