### ISSUE TITLE
Incorrect Documentation for Distributions

### ISSUE THREAD

**Issue by laurelvwhite** [gwastro/pycbc#2588]
The documentation for the uniform distribution is incorrect. The class is called prior but it is now called distributions.
```
Examples

    --------

    Create a 2 dimensional uniform distribution:



    >>> dist = prior.Uniform(mass1=(10.,50.), mass2=(10.,50.))

```

**Comment by GarethCabournDavies** [comment]
Looks like this was fixed in https://github.com/gwastro/pycbc/pull/3681
