### ISSUE TITLE
Statistic calculations are inflexible

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2593]
The statistic functions / classes in events.py and stat.py are somewhat hardcoded to allow some combinations of operations but not others; to allow all combinations would require an exponentially number of functions or classes.  

So, rework to make the calculations more additive / 'modular' in terms of combining operations, both for single-ifo stats and coincidences.

**Comment by tdent** [comment]
@GarethDaviesGW I think I mentioned this before we went to the LVC meeting.

**Comment by titodalcanton** [comment]
Did #3535 address this?

**Comment by spxiwh** [comment]
Yes
