### ISSUE TITLE
Remove upper requirement on the astropy version

### ISSUE THREAD

**Issue by mattpitkin** [gwastro/pycbc#2612]
Is there any reason for having the upper version bound on astropy (`astropy>=2.0.3,<3.0.0`) in the requirements file? Is this just that PyCBC is not yet completely Python 3 compatible yet? From looking at the locations where astropy is used in the code, and testing them with astropy v3.1.2 installed, I don't seem to see any problems.

If the issue is that not having the upper bound makes the test suite try and download a non-Python 2 compatible astropy version, you could edit the requirements file to, e.g.,

```
astropy>=2.0.3,<3.0.0; python_version <= '2.7'
astropy>=2.0.3; python_version > '3.4'
```

**Comment by ahnitz** [comment]
@mattpitkin You've exactly understood the reason. If you have a chance to patch requirement.txt (and setup.py) to add this, then that would be great. Otherwise, I should have a chance when I get back from travelling next week.

**Comment by mattpitkin** [comment]
Cool, I'll submit a patch now.
