### ISSUE TITLE
Diagnostic plots need to be optional in inference workflows

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#2616]
Currently, the PP workflow (and I think the standard workflow) hardcode what diagnostic plots -- `plot_acl`, `plot_samples`, etc. -- are created. This makes it impossible to run these with nested samplers, since many of these plots don't make sense for them. In addition, different diagnostic plots may be of interest for nested samplers.

It would be good if we which plots that get created are optional in the workflow. I'm thinking something like, you'd have a section that would specify which plots to create; something like:
```
[diagnostic_plots]
acl =
acceptance-rate =
```
Here, each of the arguments corresponds to the name of an executable. All of the options for those plots are set by their respective sections. Then, in the workflows, it would cycle over the listed plots, and only create jobs for the ones specified. The results page would then have these plots in subsections under a single tab ("Diagnostic plot?"), or a different tab for each plot (meaning the number of tabs could vary from run to run). It would then be easy to add new plots, like `plot_psd`.

I'm not sure how feasible this would be. I'm also not certain if adding the nodes could be done with a single, generic function that takes kwargs, or if it's necessary to have specific `make_{some_plot}_node` in `inference_workflows` for each type of possible plot (with a bunch of if statements in the workflow). The former would be better since you wouldn't have to add a new workflow function every time a new plotting executable is added, but may not be possible. Something has to be done though, so we can use the workflows with the nested samplers.

**Comment by ahnitz** [comment]
@cdcapano The way we've handled this in other worksflows is that if the section exists i.e [plot_coinc_snrchi] we make the plot, else not. The corresponding make_black workflow functions typically check for the key and become a noop if the option isn't in the workflow. 

You could it as described instead and that should not be very hard. The only thing required is for the plotting jobs to have the exact *same* required arguments. i..e --input-file or --output-file, etc. Then this is pretty straightforward.

**Comment by cdcapano** [comment]
Fixed by #3140.
