### ISSUE TITLE
single ifo binned hist plots in multi-ifo coinc workflow are not getting correct veto segment name

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2675]
Currently --veto-segment-name is 'closed_box' for these jobs, however these segments do not exist until after the coinc jobs are run.  The CUMULATIVE_CAT_12H veto segments which are present from the beginning of the workflow should be used for these plots.

**Comment by ahnitz** [comment]
Why shouldn't these be using the censored segments?

**Comment by tdent** [comment]
Ah, I was seeing a mismatch between the veto xml file and the name of the veto segments for the binned-histogram (rainbow) plots.  The plots are being given 
H1L1V1-CUMULATIVE_CAT_12H_VETO_SEGMENTS_CUMULATIVE_CAT_12H-start-end.xml but told to use 'closed_box' segments which do not exist.

**Comment by ahnitz** [comment]
Ah, ok, so they are being passed the wrong file.

**Comment by tdent** [comment]
Other single-ifo plots are being fed the H1L1V1-FOREGROUND_CENSOR-start-end.xml file, which does have the 'closed_box' segments.  I guess this is OK since they are mainly diagnostic/sanity. 

Specifically for the binned-histogram plots, loud signal/outliers are being removed by the 'pruning' procedure which means they are OK to get the CAT_12H segments without zerolag censoring. 

Personally I prefer this since it uses the same set of triggers as is done by the fitting code, whereas if it did both zerolag censoring and pruning it would show something different. 

So, I would prefer the binned-hist plots to use the CAT_12H segments as the fit-by-template jobs do.

**Comment by tdent** [comment]
Since these are diagnostic plots, ie don't exactly represent the fitting that is done, and the new split-binned plot does not do pruning, I think it's OK to actually use the 'foreground censor' veto file with the 'closed_box' segments.  That will remove most of the loud (coincident) triggers at least.

**Comment by tdent** [comment]
Feeding the closed box veto to the sngls split fit plot will partly address #2909 .

**Comment by GarethDaviesGW** [comment]
Fixed by #2932
