### ISSUE TITLE
Handling of tags in SplitXXX codes

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#268]
The handling of tags in the splitinspinj and splittmpltbank codes is inconsistent:

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/jobsetup.py#L1117

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/jobsetup.py#L1461

these codes are a little different from others as they inherit tags from the parent jobs and then add a split number tag. But in some cases you may want to split the parent file **more than once** using different numbers of split files (ie. for injection analysis the bank could be denser than for full-data, most relevant in GRB where sliding is done in full-data).

Alex, what do you think is the best way to handle this, should we add a extra_tags option (or something) in the "**init**" of these classes and append that to the parent's tags _and_ the split number tag?

Having these two share functions code (and be adjacent in the code) would also be good ... Maybe the executables could even be combined?

**Comment by ahnitz** [comment]
Old, re-open if still relevant.
