### ISSUE TITLE
Multiifo search requires all 'FIT_OVER' stat files to be present even if not needed for coinc job

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2685]
I see e.g. in a H1L1V1 run, 
`<job id="ID0014978" name="multiifo_coinc-FULL_DATA_FULL_2DET_H1L1-L1H1_ID27">
                <argument>--coinc-threshold 0.002 --ranking-statistic exp_fit_sg_csnr --randomize-template-order  --timeslide-interval 0.1 --loudest-keep-values 9:10 8.5:30 8:30 7.5:30 --template-bank <file name="H1L1V1-BANK2HDF-1238166018-853200.hdf"/> --trigger-files <file name="L1-HDF_TRIGGER_MERGE_FULL_DATA-1238166018-853200.hdf"/> <file name="H1-HDF_TRIGGER_MERGE_FULL_DATA-1238166018-853200.hdf"/> --statistic-files <file name="H1-FIT_OVER_PARAM-1238166018-853200.hdf"/> <file name="L1-FIT_OVER_PARAM-1238166018-853200.hdf"/> <file name="V1-FIT_OVER_PARAM-1238166018-853200.hdf"/> --veto-files <file name="H1L1V1-CUMULATIVE_CAT_12H_VETO_SEGMENTS_CUMULATIVE_CAT_12H-1238166018-853200.xml"/> --segment-name CUMULATIVE_CAT_12H --pivot-ifo H1 --fixed-ifo L1 --template-fraction-range 13/30 --output-file <file name="L1H1-MULTIIFO_COINC_FULL_DATA_FULL_2DET_H1L1_CUMULATIVE_CAT_12H_13-1238166018-853200.hdf"/></argument>`
i.e. it's a H1L1 coinc job but is being fed H1,L1,V1 fit files.  This means for instance if the H1 and L1 files are present but the V1 fit file isn't the job cannot proceed.  Would be preferable to give each coinc job only the statistic files it needs.

**Comment by spxiwh** [comment]
Ah, yeah, this can be fixed easily enough. FileLists have a `find_output_with_ifo` method so:

`statfiles_HL = statfiles.find_output_with_ifo('H1') + statfiles.find_output_with_ifo('L1')`

**Comment by tdent** [comment]
The eventual full statistic calculation *will* take in all the statistic files (although not necessarily read them all) hence close this issue.
