### ISSUE TITLE
Fix check for output file in pycbc inference

### ISSUE THREAD

**Issue by cdcapano** [gwastro/pycbc#2732]
The force option in `pycbc_inference` is currently broken. Fix it.

**Comment by soumide1102** [comment]
Probably related to this issue. One of my runs completed, the bkup file was deleted, and hdf.checkpoint replaced by the final .hdf . But condor seems to not have successfully removed the job, but started a fresh run from the 0th iteration again. So my run directory has an `inference.hdf` (from the completed run) and `inference.hdf.checkpoint`, `inference.hdf.bkup` from the new run that should not have started.

**Comment by cdcapano** [comment]
This was fixed awhile ago.
