### ISSUE TITLE
Workflow-gating section in analysis.ini is useless

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2776]
See 
https://github.com/gwastro/pycbc-config/blob/master/test/analysis.ini#L78 
and 
https://github.com/gwastro/pycbc-config/issues/59
and  
#2373 

Remove, adding an informative comment and/or add a gating.ini file or set of options that does something.

**Comment by spxiwh** [comment]
Moved to the various open issues/PRs on this.
