### ISSUE TITLE
Trying to merge time series

### ISSUE THREAD

**Issue by anushri22** [gwastro/pycbc#2797]
I am trying to add time series together by using the add_into() function.
My code is trying to add a 'big' waveform and a 'small' one. I double checked and they have the same delta_t but somehow the operation thinks they're different.

    ValueErrorTraceback (most recent call last)
    <ipython-input-51-7f63e58f4476> in <module>()
          2 waveform_big_test = waveform_big_hp[:]
          3 
    ----> 4 overlapping_signal = waveform_big_hp.add_into(waveform_smol_hp)
          5 
          6 

    3 frames
    </usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-153> in __iadd__(self,     other)

    </usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-152> in __iadd__(self, other)

    /usr/local/lib/python2.7/dist-packages/pycbc/types/timeseries.pyc in _typecheck(self, other)
         91         if isinstance(other, TimeSeries):
         92             if other._delta_t != self._delta_t:
    ---> 93                 raise ValueError('different delta_t')
         94             if self._epoch != other._epoch:
         95                 raise ValueError('different epoch')

    ValueError: different delta_t

**Comment by ahnitz** [comment]
@anushri22 Thanks for reporting this. Do you have a reproducing case? If not, we'll see if we can find one. My first guess is there is probably a floating point level difference here in the time step and that we should probably allow for this level of uncertainty.

**Comment by ahnitz** [comment]
@anushri22 I think this is likely due to a strict check on the dt. We are thinking about a proposed solution here (https://github.com/gwastro/pycbc/pull/2819).

**Comment by ahnitz** [comment]
We've since made this a less stringent test, so hopefully this should be resolved. Please re-open if this is not the case.
