### ISSUE TITLE
Multi-ifo p/t/a consistency

### ISSUE THREAD

**Issue by GarethDaviesGW** [gwastro/pycbc#2854]
add in p/t/a consistency statistic into multi-ifo search

**Comment by tdent** [comment]
Addressed by #2830

**Comment by GarethDaviesGW** [comment]
@ahnitz are we happy that the 3-ifo p/t/a is added in and is all working fine? We can probably close this issue if it is

**Comment by tdent** [comment]
1. #2943 is still open 
2. has not been tested against the previous implementation of 2-ifo pta or against the 3-ifo 'geometric average' pta stat as far as I know

**Comment by GarethDaviesGW** [comment]
Sorry for delay on this issue, I have tested against the geometric average method and 2943 is merged. I don't think we need any more testing on this and the issue can be closed
