### ISSUE TITLE
inference should fail early when trying to get PSD from empty data range

### ISSUE THREAD

**Issue by dbkeitel** [gwastro/pycbc#2857]
A while ago we noticed that pycbc_inference can happily run, but not sample anything, for a long time on GWOSC frames where the detector only turns on close to the trigger time, but after psd-start-time; i.e. the data is 0 or NaN or whatever GWOSC put in there. In that specific case, shifting the PSD window to be mostly after the trigger helped, so we didn't pursue it further yet.

So we haven't debugged this deeper yet, but probably a zeros/NaNs check on the PSD and/or the raw data inside the PSD window itself would be sufficient to make such a run abort straight away.

Should we start looking into it, or does anyone have anything similar lying around already?

**Comment by cdcapano** [comment]
@ahnitz @spxiwh This seems like something that should be in the strain module. Is there any work to make the strain module automatically check for NaNs when loading GWOSC files?

**Comment by cdcapano** [comment]
Fixed by #3091
