### ISSUE TITLE
Minifollowup of coinc events for ifos searched but not triggering

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2882]
Followup plots should be made in times when the detector is running, but did not trigger (see first event in https://ldas-jobs.ligo.caltech.edu/~gdavies/analyses/multiifodev/a20_exclude_zerolag_v2/7._open_box_result/7.01_loudest_events_followup/)

**Comment by tdent** [comment]
Is this solved?

**Comment by GarethDaviesGW** [comment]
not yet. it's in my list - Ian pointed out an issue with my solution on the PR so will get on with that when I can
