### ISSUE TITLE
multiifo FAP appears to be bugged

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2883]
The FAP of loud events now seems to be wrong: i.e. 1.00 rather than v small 
(eg https://ldas-jobs.ligo.caltech.edu/~gdavies/analyses/multiifodev/a20_exclude_zerolag_v2/7._open_box_result/7.01_loudest_events_followup/ )
Check FAP calculation (should be in add_statmap)

**Comment by GarethDaviesGW** [comment]
should be addressed by #2884

**Comment by tdent** [comment]
fixed by #2884
