### ISSUE TITLE
coincinfo seems to be producing garbage information for multi-ifo workflow

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#2894]
Obvious sign of something wrong is that there are trigger times which are >>> than the TOF being reporting by pycbc_page_coincinfo for *some* but not all triggers in a multi-ifo workflow. 

My guess is there may be a bug in the trigger_id handling for multi-ifo workflow. I'll look into this.

**Comment by ahnitz** [comment]
Example wrong information. https://www.atlas.aei.uni-hannover.de/work/ahnitz/projects/2-ogc/bbh/test/three/O2/21-1/output/local-site-scratch/work/gw-main_ID0000001/H1L1V1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_DATA-1186624818-687900/H1L1V1-PAGE_COINCINFO_1-1186624818-687900.html

**Comment by tdent** [comment]
Can this be reproduced?  I'm not seeing anything like this, including runs from recent master.

**Comment by tdent** [comment]
Expect to be fixed by #2922 .
