### ISSUE TITLE
test_almost_equal_mass_waveform in test_lalsim.py doesn't seem to test anything

### ISSUE THREAD

**Issue by SergeiOssokine** [gwastro/pycbc#2896]
Currently the function `test_almost_equal_mass_waveform` in `test/test_lalsim.py` contains no asserts and doesn't appear to test anything (except actually generating near equal mass waveforms, although this would produce an ERROR and not a FAIL currently). Is this the intended behaviour?

**Comment by spxiwh** [comment]
This was the intention. We observed some Phenom (or EOB, I don't remember) cases, where numerical accuracies at almost-equal mass ended up with eta being computed as 0.2500001 and then NaNs appeared further down the line. So this just checks that these cases don't ERROR. Improvements to this script are always welcome, it's probably used by waveform folks more than by the core PyCBC team.

**Comment by SergeiOssokine** [comment]
OK, makes sense, thanks!
