### ISSUE TITLE
pycbc_fit_sngls_split_binned missing some features

### ISSUE THREAD

**Issue by GarethDaviesGW** [gwastro/pycbc#2909]
`pycbc_fit_sngls_split_binned` does not have the same features as `pycbc_fit_sngls_binned`, which it is designed to mimic/replace/upgrade. Namely these are:
 - defaults the `bin-param` to be logarithmically spaced and does not have capability to change this
 - does not perform any pruning (this was simply due to ignoring it at the stage of writing)

These should be amended/added at some point

**Comment by tdent** [comment]
is this now done?

**Comment by GarethDaviesGW** [comment]
Yes, sorry, not been keeping track of the issues the way I should
