### ISSUE TITLE
`pip install pycbc` fails on arm64

### ISSUE THREAD

**Issue by steffen-AEI** [gwastro/pycbc#2927]
```
[...]
    creating build/temp.linux-ppc64le-3.5
    creating build/temp.linux-ppc64le-3.5/pycbc
    creating build/temp.linux-ppc64le-3.5/pycbc/waveform
    powerpc64le-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-NVmvUW/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -c pycbc/waveform/spa_tmplt_cpu.c -o build/temp.linux-ppc64le-3.5/pycbc/waveform/spa_tmplt_cpu.o -O3 -w -msse4.2 -ffast-math -ffinite-math-only -fopenmp
    powerpc64le-linux-gnu-gcc: error: unrecognized command line option ‘-msse4.2’
    error: command 'powerpc64le-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qa4fzbxw/pycbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qa4fzbxw/pycbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4y97_xu_/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```
SSE4.2 is not available on POWER{8,9}. I guess something similar would happen on arm64?

**Comment by ahnitz** [comment]
@steffen-AEI If we want it to build on those platforms we may need to add a check in setup.py on the architecture capabilities or likewise. The compile flags are hardcoded in setup.py atm.

**Comment by steffen-AEI** [comment]
Yes, please do, and count me in for testing ;)

**Comment by titodalcanton** [comment]
@steffen-AEI after #2936 makes it into a release, this should be fixed.

**Comment by titodalcanton** [comment]
@steffen-AEI have you had a chance to try `pip install pycbc` on a non-x86 architecture recently? Can you close this if it works?

**Comment by titodalcanton** [comment]
I verified that on a Raspberry Pi the latest release of PyCBC installs ok with `pip`, although I do not have a working lalsuite to really check any functionality.

**Comment by steffen-AEI** [comment]
On Tue, 2019-11-26 at 09:17:25 -0800, Tito Dal Canton wrote:
> I verified that on a Raspberry Pi the latest release of PyCBC installs ok with `pip`, although I do not have a working lalsuite to really check any functionality.

https://git.ligo.org/lscsoft/lalsuite/issues/202

-- 
Steffen Grunewald, Cluster Administrator
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Am Mühlenberg 1 * D-14476 Potsdam-Golm * Germany
~~~
Fon: +49-331-567 7274
Mail: steffen.grunewald(at)aei.mpg.de
~~~

**Comment by titodalcanton** [comment]
After building lalsuite on the Raspberry Pi, I can verify that PyCBC installs with `pip` and basic functionality works (I have not ran the full test suite).

**Comment by chunyulin** [comment]
On arm64, I cannot install pycbc-1.16.7 from source due to the missing of "x86intrin.h", which seems to be related to the SIMD staff. My workaround is to comment the following lines in setup.py and it works for most inference job. Can I just comment those line? 

#e = Extension("pycbc.events.simd_threshold_cython",
#              ["pycbc/events/simd_threshold_cython.pyx"],
#              language='c++',
#              extra_compile_args=cython_compile_args,
#              extra_link_args=cython_link_args,
#              compiler_directives={'embedsignature': True})
#ext.append(e)
#e = Extension("pycbc.filter.simd_correlate_cython",
#              ["pycbc/filter/simd_correlate_cython.pyx"],
#              language='c++',
#              extra_compile_args=cython_compile_args,
#              extra_link_args=cython_link_args,
#              compiler_directives={'embedsignature': True})
#ext.append(e)

**Comment by ahnitz** [comment]
@chunyulin For most inference you should be OK with commenting that out, though we need to find a longer term solution if we want to fully support ARM.

**Comment by BenjaminDbb** [comment]
> @chunyulin For most inference you should be OK with commenting that out, though we need to find a longer term solution if we want to fully support ARM.

Hi, I wonder if there is a plan/timeline for supporting OSX-Arm64?

**Comment by ahnitz** [comment]
@BenjaminDbb I think we are primarily limited by the lack of access to the hardware. None of the primary developers have upgraded to an M1 mac and I myself don't have a Mac of any kind. Of course, if someone has an M1 mac and is able to submit PRs, we'd be happy to accept them. 

If you want a rough timeline, it's probably whenever @cdcapano buys a new computer. I suspect he's the most likely to be able to test on that hardware in the future. That's a pretty nebulous timescale unfortunately.

**Comment by BenjaminDbb** [comment]
@ahnitz Thank you for your reply.

**Comment by cdcapano** [comment]
@BenjaminDbb I actually have recently purchased an M1 mac mini, but haven't had a chance to try pycbc on it yet. It's not my work computer, so it's mostly what I can do in my spare time. I plan to try it out sometime soon, but this is low on the priority list for me at the moment, sorry.
