### ISSUE TITLE
Add inj snr/chisq plots to multi-ifo workflow

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2933]
They don't seem to be being made.

**Comment by tdent** [comment]
Looks like the snr/chisq plot script needs to be rewritten to not assume 2-ifo file format.

**Comment by tdent** [comment]
Is this still open?

**Comment by GarethDaviesGW** [comment]
yes, still open. Me and @spxiwh went through the currenlty not being plotted things and this is one of them. We also want to check that they're correct in the 2-ifo case as there are some weird results at the moment

**Comment by GarethDaviesGW** [comment]
Solved in #3220
