### ISSUE TITLE
Add global IFAR plot for multi-ifo pipeline

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2962]
While we can't assign IFARs to time slides in the multi-ifo pipeline globally (ie over all coinc types) we can show the foreground IFARs against the expected noise count. Eg this made from an O2 chunk 20 run - 
![image](https://user-images.githubusercontent.com/3316412/66209369-7c47e180-e6b7-11e9-85d9-cbbdd15f2e0a.png)
The code to produce the plot exists (PR #2961), it may need some plumbing to insert into the pipeline.

**Comment by GarethDaviesGW** [comment]
Fixed by #3078
