### ISSUE TITLE
Redundant parameter in super.__init__ function of marginalized_gaussian_noise causes serious problem

### ISSUE THREAD

**Issue by xiaoliangastro** [gwastro/pycbc#2974]
For version 1.14.2, in file pycbc/inference/models/marginalized_gaussian_noise.py, at line 366, the parameter 'waveform_generator' mismatch with parameters of __init__ function of GaussianNoise. I delete that line on my PC, it works well, otherwise it will raise a serious problem.

**Comment by cdcapano** [comment]
This class was removed from the models with #3108 as there were several other bugs in it.
