### ISSUE TITLE
Fake data SEOBNRV4 injections sample frequency problems

### ISSUE THREAD

**Issue by GarethDaviesGW** [gwastro/pycbc#2979]
When generating fake coloured Gaussian noise data, some inspiral jobs were failing with SEOBNRV4 injections

Error as follows:
```
XLAL Error - XLALSimIMRSpinAlignedEOBWaveformAll: Ringdown frequency &gt; Nyquist frequency!
At present this situation is not supported.
XLAL Error - XLALSimIMRSpinAlignedEOBWaveformAll (LALSimIMRSpinAlignedEOB.c:980): Input domain error
XLAL Error - XLALSimInspiralChooseTDWaveform (LALSimInspiral.c:920): Internal function call failed: Input domain error
```

Slack discussion when this was brought up:

Thomas Dent
@ Gareth Davies just a note to make sure that we don’t forget, you said you had some ‘ringdown>Nyquist’ failures in SEOBNRv4 injections in a run on gaussian noise. when you get a chance, would be good to try and work out where these are coming from

Ian Harry
Ah, when running on Gaussian noise the noise is generated at the sampling frequency (4096Hz) not at the 16384Hz that data is normally sampled at ... There is then no downsampling. But SEOB in particular doesn't like being generated at 4096Hz, so this might cause failures

Maybe we need an option to do downsampling on Gaussian noise to avoid this??

Thomas Dent 
SEOBNRv3 worked, for some reason

Alexander Harvey Nitz
@ Ian Harry @ tdent If you want SEOBNRv4, you could just inject the ROM version. That shouldn't have problems at lower sample rates.

Ian Harry
v3 has that failsafe hack, where it will generate again at higher sample rate if it fails initially
(Adding v4 there is another potential method to getting v4 to generate)

Thomas Dent
Well, we aren’t really needing to inject SEOBNRv4 over the whole space from component mass 2 upwards
@ Ian Harry though, why are you stating 4096Hz - standard analysis sampling rate is 2048Hz

Alexander Harvey Nitz
@ tdent I think just a thinko, it's resampled first to the requested sample rate before injections are made. https://github.com/gwastro/pycbc/blob/master/pycbc/strain/strain.py#L381
pycbc/strain/strain.py:381
            strain = resample_to_delta_t(strain, 1.0/opt.sample_rate)
￼gwastro/pycbc | Added by GitHub

Thomas Dent
@ Alexander Harvey Nitz hang on, how does the colored_noise function know what sampling rate to use before resampling?

Alexander Harvey Nitz
@ tdent It only produces noise at 16384 Hz atm.
Somewhat not-obvious how to make it reproduceable otherwise.
(unless we give up producing the same time series at different sample rates)

**Comment by tdent** [comment]
fixed by #2981
