### ISSUE TITLE
Can pycbc_cohptf_efficiency be removed?

### ISSUE THREAD

**Issue by duncanmmacleod** [gwastro/pycbc#3029]
The script [`bin/pygrb/pycbc_cohptf_efficiency`](https://github.com/gwastro/pycbc/blob/f488f601d97bba3689785a6eb8a61aa328c4d911/bin/pygrb/pycbc_cohptf_efficiency) has every single line commented out, and yet is still being installed. This makes automatic testing of builds every difficult, because this script clearly shouldn't be there.

Can it be removed from the repo? Please.

**Comment by ahnitz** [comment]
I assume that some combination of @pannarale or @idorrington92 would know if this can be removed. I agree though with @duncanmmacleod it certainly seems like it should be if it's all commented out.

**Comment by pannarale** [comment]
Sorry, I had missed notifications from this issue (thanks @titodalcanton for pointing me to this).

This script was added here as a place holder for future work (planning to rewrite it in pycbc next semester).  It can be removed.  I hadn't even realized it had been committed.
