### ISSUE TITLE
distribute wheels

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#3034]
Now that we've ditched weave, we should distribute wheels to pypi to make it faster for people to download and to drop the requirement for someone to have a build environment to run pycbc.

At minimum we should build wheels for all combinations of
pycbc27 python36
LinuxMany, MaxOS (whatever travis supports, sorry to people with older versions).

**Comment by titodalcanton** [comment]
Fixed by #3625?

**Comment by ahnitz** [comment]
Indeed, we can close this now.
