### ISSUE TITLE
Write PyCBC library paper so there is a single citation for use of PyCBC

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#3073]
Astropy has a library paper published in A&A that all users of astropy are asked to cite:

https://ui.adsabs.harvard.edu/abs/2013A%26A...558A..33A/abstract

Currently we ask people to cite a mix of things: GitHub (which doesn't accumulate citations), Zenodo DOIs for releases (which means that citations don't clock up over releases, and generic use of the library may be uncited), and the publications describing specific methods and algorithms when used.

Obviously we still want people to cite method and algorithm papers, but we need a single library paper that we request everyone cites so that PyCBC can clock up citations.

**Comment by duncan-brown** [comment]
To illustrate the issue, according to INSPIRES-HEP, PyCBC is [mentioned in 188 papers](https://inspirehep.net/search?ln=en&p=find+fulltext+%22pycbc%22) but the most cited methods paper (Usman et al.) only has 172 citations and is really only relevant to searches.

**Comment by tdent** [comment]
Well is this really 'an issue'? And who is envisioned to be on the author list of this extra, citation-clocking-up paper? Is there also a reverse risk that people will stop citing specific method papers and think that citing the generic paper is sufficient?

**Comment by tdent** [comment]
Also, in general 'write paper solely in order to get citations' is not a philosophy I particularly go for.

**Comment by ahnitz** [comment]
@tdent Anyone who has contributed to PyCBC should be able to opt-in as an author. 
At the moment, the issue is that zenodo is not particularly tracked well, so it isn't clear when the software is being used. There is also the issue that many people have contributed and their efforts are not reflected in any existing publications. For use of specific algorithms  / programs where methods papers are already available (i.e. pycbc inference, pycbc live, pycbc offline, etc), our advice won't change from what it currently is in the citation guidelines.

**Comment by ahnitz** [comment]
Nobody has time to do this. reconsider if someone gains interest or there is more utilitity to doing it.
