### ISSUE TITLE
Multi-ifo: Results page used optimal SNR in CAT2 vetoed time when ordering injection followup

### ISSUE THREAD

**Issue by connor-mcisaac** [gwastro/pycbc#3109]
In the injections followup section of a 3 detector run the top injections had optimal SNRs of:
H1: 8.20
L1: 11.40
V1: 1.46
However, H1 was in CAT2 vetoed time. The page is ordered by the 2nd highest optimal SNR for available detectors.
With the 2nd highest being V1 at 1.46 this should not have been (or been at the bottom of) on the followup list.

**Comment by GarethDaviesGW** [comment]
I am fairly sure that this is solved by #3321, where optimal SNR is set as zero for vetoed injections, but you might want to confirm that this is the case

**Comment by GarethDaviesGW** [comment]
As mentioned above - I think that this was solved by #3321, and havent seen any issues with this since
