### ISSUE TITLE
Three-detector coinc jobs to be optimised

### ISSUE THREAD

**Issue by GarethDaviesGW** [gwastro/pycbc#3143]
In a workflow with equal parallelization between 3det and 2det coincs, the three-detector coincidence jobs were using 30Gb memory, compared to around 1.5Gb for the two-detector coinc jobs

We (Gareth, Tom, Ian) think that this should be something that we can make more efficient/optimize, but this will wait until after the multiIFO methods paper is out

Reminder issue

**Comment by GarethDaviesGW** [comment]
Just to connect some dots - @connor-mcisaac is working on this in #3345

**Comment by spxiwh** [comment]
#3345 will mostly only have affect on the *2-ifo* jobs. I think the 3-ifo memory issue was addressed already in other patches (e.g. presorting the 3-ifo array and storing with fewer bits). I'll close this.
