### ISSUE TITLE
is there any typo?

### ISSUE THREAD

**Issue by yanyuechuixue** [gwastro/pycbc#3160]
https://github.com/gwastro/pycbc/blob/8161365fe6e5e86f0ac591dc62651251f2ed4b54/pycbc/inference/sampler/multinest.py#L405

maybe it should be 
``` python
obj.setup_output(output_file)
```

**Comment by cdcapano** [comment]
Yes, that's a bug, thanks for catching. I've filed a pull request to fix it.

**Comment by cdcapano** [comment]
Fixed by #3162.
