### ISSUE TITLE
Dynesty doesn't support sampling transform either

### ISSUE THREAD

**Issue by yi-fan-wang** [gwastro/pycbc#3168]
In the line 69 and 70 of pycbc/inference/sampler/base_cube.py

>         if model.sampling_transforms is not None:
>             raise ValueError("Ultranest does not support sampling transforms")

But dynesty also raises the error because it doesn't support sampling transforms either, if my understanding is correct. We can change "Ultranest" to "Ultranest or dynesty" to make the message more accurate.

**Comment by ahnitz** [comment]
@yi-fan-wang Good point, can submit a PR to fix this?

**Comment by yi-fan-wang** [comment]
@ahnitz Sure

**Comment by JohannesBuchner** [comment]
Why is this not possible to support? I would think such transforms could be expressed as inverse CDFs as well, and applied in sequence when sampling from the prior.

For example, a exponential transform would change 

```
        for i, param in enumerate(self.model.variable_params):
            cube[i] = dist_dict[param].cdfinv(param, cube[i])
```

to

```
        for i, param in enumerate(self.model.variable_params):
            cube[i] = 10**((dist_dict[param].cdfinv(param, cube[i]) - log10(lo)) / (log10(hi) - log10(lo))
```

while a normal transform (of 10+-5) may be:

```
        for i, param in enumerate(self.model.variable_params):
            cube[i] = scipy.stats.norm(10, 5).ppf(param, cube[i])
```

**Comment by ahnitz** [comment]
I think this won't be fixed. Although it can be handled with explicit distributions, or the new fixed Sample distribution for the cases where that is appropriate.
