### ISSUE TITLE
epsie should not be hard-required

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#3178]
Espsie imports still leak in when running inference code. @cdcapano Can you sanitize these so epsie is not a hard requirement.

**Comment by dbkeitel** [comment]
I just ran into missing `epsie` as well when just doing
`from pycbc.inference.option_utils import prior_from_config`, so this is a problem even when not running an actual sampler.

**Comment by ahnitz** [comment]
@cdcapano Can you please fix this as high priority.
