### ISSUE TITLE
Use of `hist` attribute as dummy attribute in New stat classes

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3222]
From #3204 . `self.hist` is misused in the new PhaseTime statistic class, which seems to be a holdover from copy-pasting from a previous class. @tdent says

"""
The attribute self.hist isn't used to store a histogram in any of the methods of this class anyway! One of you has now put the actual histogram heights into weights or two_det_weights instead. (And I don't know why we would call them 'weights' .. a weighted histogram is something different.) So self.hist just seems to be a flag to indicate whether the histogram has been read in and 'created' properly or not, which should be a Boolean if it's not carrying any other information.

(I don't see where subclasses are an issue, this looks like cut and paste from previous code where self.hist did contain actual data.)

In any case can't this bookkeeping of whether or not the histogram has been read in yet be dealt with more simply by making the 'histogram reading' part of __init__ ?
Ie would anything go wrong if that was the case?
"""

Moving this to `__init__` would slow down the "no-op" case, where if the code doesn't need to compute *any* coincidences it will take a while to do that. Maybe that doesn't matter?

(We may need to consider a hack day in the Summer to try to re-organize this module, #2593 is probably another thing to be resolved??)

**Comment by tdent** [comment]
You are correct that things here (and also in ranking.py) should be reorganized. This has been something on my to-do list for many months, and probably cannot be done quickly by throwing people at it for a few hours, and there have been, not surprisingly, many other things that have taken priority.

**Comment by tdent** [comment]
& if I'm allowed to suggest another change, histogram values should be called 'heights' not 'weights'.

**Comment by ahnitz** [comment]
Seems to be addressed
