### ISSUE TITLE
Direct float comparison 

### ISSUE THREAD

**Issue by Sbozzolo** [gwastro/pycbc#3226]
https://github.com/gwastro/pycbc/blob/812b518c61e2cf26dfe79eb91ceec19c666b08c4/pycbc/filter/matchedfilter.py#L1237

Here two floating-point numbers are compared with an `==` operator. This test can fail due to the finite precision of the floats. Is there any reason why `==` is used instead of the following ?
```python
try:
    numpy.testing.assert_almost_equal(stilde.delta_f, psd.delta_f)
except:
    raise TypeError("PSD delta_f does not match data")
qtilde[kmin:kmax] /= psd[kmin:kmax]
```

**Comment by ahnitz** [comment]
I don't think so anymore. I think we'd be happy to accept a PR to change this if you would find it useful.

**Comment by Sbozzolo** [comment]
See #3227. I also fixed a bare `except` and I changed `TypeError` to `ValueError`.
