### ISSUE TITLE
It seems that there is a typo.

### ISSUE THREAD

**Issue by yanyuechuixue** [gwastro/pycbc#3231]
https://github.com/gwastro/pycbc/blob/e5f6325e15b978adf2e4d93ea64ff23b9c811cfa/examples/inference/bbh-injection/injection.ini#L9

It should be ``` inclination ``` right?

Thanks all.

**Comment by micamu** [comment]
Indeed, thanks for spotting this! It will get fixed as soon as #3233 gets merged.
