### ISSUE TITLE
time series add_into alignment error

### ISSUE THREAD

**Issue by MarlinSchaefer** [gwastro/pycbc#3243]
When using the add_into function of a TimeSeries with a TimeSeries where the epoch is not exactly the same as the one of the original TimeSeries, a ValueError 'different epoch' is raised. This happens even if the epoch is manually set to floating point precision to be: original epoch + integer * original delta_t. The reason seems to be an internal check, where the GPS times are compared rather than the floating point representations. I've [attached a script](https://github.com/gwastro/pycbc/files/4558350/add_into_bug.txt) showcasing both manual alignment and random starting times.

**Comment by ahnitz** [comment]
This should be fixed by #3244
