### ISSUE TITLE
Single_template inference model doesn't accept TD templates

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3249]
It would be nice if the single_template model could use a TD single-template, as FD waveforms are fast anyway, and it doesn't matter so much if you regenerate FD waveforms.

**Comment by ahnitz** [comment]
Assigning to me as I wrote the model.

**Comment by ahnitz** [comment]
@spxiwh Thinking about this a bit. Is this just another form of #3251 ? I.E. shouldn't the td waveform come through the get_fd_waveform_from_td interface? Or are you thinking one should allow a direct conversion as well?

**Comment by spxiwh** [comment]
Duplicate. Closing.
