### ISSUE TITLE
Update cookie handling (long term, not urgent)

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#3301]
We should try and integrate https://github.com/duncanmmacleod/requests-ecp/, which is being set up by @duncanmmacleod as a backend to both ecp-cookie-init and ligo-proxy-init, but hopefully we can use directly

**Comment by GarethCabournDavies** [comment]
I think this is done now, but will check with @duncanmmacleod

**Comment by duncanmmacleod** [comment]
I _think_ so, but am not really a user of pycbc or a core developer, so am not 100% clued in.

**Comment by GarethCabournDavies** [comment]
I'm going to close this, as we are not requiring ecp-cookie-init or ligo-proxy-init anymore, and I think we are fully integrated okay now
