### ISSUE TITLE
Hash handling in offline templates

### ISSUE THREAD

**Issue by GarethDaviesGW** [gwastro/pycbc#3302]
Template hashes can clash in the python3 version of the hash() function

@titodalcanton noticed this issue in PyCBC Live #3263 and it was solved in Live by #3291 - we need to ensure that it is fixed in offline before being able to run in python 3.

Possible options are to follow the currently used live example and compare (possible float comparison issues) or use hashlib module  (_may_ still clash but v. unlikely, I think the library is more stable than the in-built function)

**Comment by ahnitz** [comment]
One can't follow the live model, as it didn't actually need to use hashes to check for common templates between different files later on. Each process still had access to the whole bank (and hence what the ids meant) so it could avoid the hashes entirely. 

I think the options are
1) hashlib (as you suggest, might be an easiest extension)
2) get rid of hashes altogether, and put an explicit id column in the banks (or at least sub-banks). This would require a few more places to change though, but would get rid of the hash issue entirely.

**Comment by ahnitz** [comment]
I believe @GarethDaviesGW has now addressed this.
