### ISSUE TITLE
Is there any documentation about how to configure a computer to run workflow?

### ISSUE THREAD

**Issue by yanyuechuixue** [gwastro/pycbc#3303]
Hello all,

I can run pycbc_inference on my local machine.
Now I want to run a workflow. (Because I want to remove a lot of injections whose snr < 8, and workflow has an option to set a thorshold.)
However, I can not find any documentation about how to set up a machine.

Is there any documentation?

Thank you all.

**Comment by ahnitz** [comment]
@yanyuechuixue There isn't at the moment, I believe @cdcapano is working on some, which will hopefully be ready in the next couple weeks.

**Comment by cdcapano** [comment]
@yanyuechuixue Yes, I'll be adding documentation for the PE workflow in the next week.

**Comment by ahnitz** [comment]
@yanyuechuixue There is updated documentation that @cdcapano made now here. https://pycbc.org/pycbc/latest/html/workflow/pycbc_make_inference_workflow.html

**Comment by ahnitz** [comment]
@yanyuechuixue The assumption for the workflows is that you have access to a condor-based compute cluster.

**Comment by yanyuechuixue** [comment]
Thank you very much!
