### ISSUE TITLE
Prepend falsely saves data in TimeSeries

### ISSUE THREAD

**Issue by MarlinSchaefer** [gwastro/pycbc#3387]
When prepending <x> zeros to a TimeSeries and then accessing the content of the TimeSeries through a slice(len(TimeSeries)-<x>, len(TimeSeries)) it returns an empty array. This happens because the roll function seems to falsely store the data to the TimeSeries._saved dict.
This bug is only an issue, when one tries to access exactly the amount of time at the end of the TimeSeries that was prepended.
(See the [attached script](https://github.com/gwastro/pycbc/files/4947078/prepend_zeros_issue.py.txt) for details.)

**Comment by ahnitz** [comment]
@MarlinSchaefer Yes, this looks like a bug. See this line https://github.com/gwastro/pycbc/blob/master/pycbc/types/array.py#L828

There is a reset of the cache, but there are a few calls to self[start:end] before the data is updated. The reset should happen at the end. @MarlinSchaefer Can you prepare a patch?

**Comment by ahnitz** [comment]
Fixed by #3389
