### ISSUE TITLE
Lowpass filter with resampling

### ISSUE THREAD

**Issue by iurilarosa** [gwastro/pycbc#3400]
Hello everyone.
This is more a feature request than an issue. I need to apply a cutoff to the time series of real data, basically to reduce their size and be able to do some faster tests on them.
For example taking the frame files from O2, I want to cut them at 256 Hz, reducing in this way the sample frequency from ~16 kHz to 512 Hz. With `lowpass_fir` this can't be done as far I can see, since it damps significantly the frequencies above the threshold but it doesn't resample the frames. 
![lowpassing](https://user-images.githubusercontent.com/16984873/88908367-0e7a3100-d25a-11ea-8d8b-c7713cdaeef2.png)
If I want to resample the time series there is `resample_to_delta_t` which in turn looks quite weird. It looks that doesn't apply a cut to the frequencies but it shrinks all the spectral features in a smaller frequency interval, but I'm not even so sure about that.
![resampling](https://user-images.githubusercontent.com/16984873/88908405-1afe8980-d25a-11ea-8259-0ef0cf124ef6.png)
So it would be nice to have something like a `pycbc.filter.cut` function that returns a time series with a spectra similar to the original one, but cut at a certain frequency. I don't know if it already exists or if it's even feasible, in this case I apologize. Thanks in advanze.

**Comment by ahnitz** [comment]
@iurilarosa Thanks for the feature request. I don't think this should be too difficult to add. As for the result you are seeing with resample_to_delta_t, this does not seem right, so I've added a bug label for the possibility that there is some issue here. 

Could you provide a reproducing case for the latter plot? I'd like to check what is happening there.

**Comment by ahnitz** [comment]
@iurilarosa BTW, resample_to_delta_t *should* work for the case you are requesting. It only supports resampling by powers of 2, but that's the case I believe you should be in.

**Comment by iurilarosa** [comment]
Hello Alex, thanks for the answer.
This is a sample of the code that I'm using:
```
data1 = pycbc.frame.read_frame(path, 'H1:DCH-CLEAN_STRAIN_C02')
psd1 = pycbc.psd.welch(data1, seg_len = 4096, seg_stride = 4096)
data1_resampled = pycbc.filter.resample.resample_to_delta_t(data1, 1/2048)
psd1_resampled = pycbc.psd.welch(data1_resampled, seg_len = 4096, seg_stride = 4096)
pylab.loglog(psd1.sample_frequencies, numpy.sqrt(psd1), label='not resampled')
pylab.loglog(psd1_resampled.sample_frequencies, numpy.sqrt(psd1_resampled), label='resampled')
print(pycbc.__version__)

Out: 1.14.1
```
![image](https://user-images.githubusercontent.com/16984873/88925438-d46a5880-d274-11ea-83b5-2448b382efff.png)

As you can see, changing the frequency of the cat to 1024, the PSD converges to the original one, but still shows all those ugly lines.

**Comment by ahnitz** [comment]
@iurilarosa In case it matters what GPS times does this cover?

**Comment by ahnitz** [comment]
@iurilarosa What you are seeing is just spectral leakage. Your PSD in the first instance is using too little data to prevent bleeding of the low frequency peak downwards. You keep the number of samples the same for your downsampled data, but keep in mind that means the *duration* of each chunk used for psd estimation is different. In fact you use 8x longer duration in the second one, which allows you to avoid the spectral leakage. See below where I've done small addition to your script. 


```
import pycbc.filter
import pycbc.psd
import pylab
import numpy

data1 = ts.copy()
data1_resampled = pycbc.filter.resample.resample_to_delta_t(data1, 1./2048)

# This just calls the same functions you used, but the option is in 
# *seconds* instead of samples
psd1_resampled = data1_resampled.psd(0.25)
psd1 = data1.psd(2)

pylab.figure()
pylab.loglog(psd1.sample_frequencies, numpy.sqrt(psd1), label='not resampled')
pylab.loglog(psd1_resampled.sample_frequencies, numpy.sqrt(psd1_resampled), label='resampled')

psd2_resampled = data1_resampled.psd(16)
psd2 = data1.psd(16)

pylab.figure()
pylab.loglog(psd2.sample_frequencies, psd2 ** 0.5, label='not resampled')
pylab.loglog(psd2_resampled.sample_frequencies, psd2_resampled ** 0.5, label='resampled')
```
![download (14)](https://user-images.githubusercontent.com/2206534/88937386-629a0b00-d284-11ea-9b8a-9a26aeaf3799.png)
![download (15)](https://user-images.githubusercontent.com/2206534/88937393-64fc6500-d284-11ea-8e34-fa0b30c069ba.png)

**Comment by iurilarosa** [comment]
Ok thank you! I totally forgot that changing the sample frequency I was reducing the amount of bits used for the PSD estimation, giving seg_len = frame_len. I was able to reproduce your plot using the attribute `.psd(16)`, and looking at the source code, also with the function `psd.welch()` in this way:
```
seglen = 16 * data1.sample_rate
segstride = numpy.int(seglen)
psd1 = pycbc.psd.welch(data1, seg_len = seglen, seg_stride = segstride)
psd1_resampled = pycbc.psd.welch(data1_resampled, seg_len = seglen, seg_stride = segstride)
```
I think that the problem is solved, at the end everything was working properly, I was just missing the point of estimating a PSD. Thank you so much!
