### ISSUE TITLE
Install MKL properly in Travis

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3463]
We should try and install MKL properly in Travis. This page might provide the necessary invocations to do this:

https://software.intel.com/content/www/us/en/develop/articles/installing-intel-parallel-studio-xe-from-apt-repository.html

**Comment by spxiwh** [comment]
@josh-willis says `Is there a reason not to just pip install mkl as we do inside the docker container, for the Travis tests?`

**Comment by ahnitz** [comment]
no longer relevant
