### ISSUE TITLE
Inclination angle  in models/single_template.py

### ISSUE THREAD

**Issue by haris-mk** [gwastro/pycbc#3515]
https://github.com/gwastro/pycbc/blob/master/pycbc/inference/models/single_template.py#L137

shouldn't it be 

ic = numpy.cos(p['inclination'])
ip = 0.5 * (1.0 + ic * ic)
htf = (fp * ip + 1.0j * fc * ic) / p['distance']

?

**Comment by ahnitz** [comment]
@haris-mk Looks like the convention may be swapped. I think you want to swap it you may also need to add a sign to htf factor for the cross term, i.e. -1.0j. 

I've verified in the past that this model passes p-p tests, but it would be better to avoid confusion and keep the convention standard.

**Comment by haris-mk** [comment]
@ahnitz It is not clear to me. 
I think the antenna patter-inclination angle combination should be always  
$`f_+ \frac{1+cos^2 \iota}{2}`$ and $`f_\times cos \iota `$.

Further, is there any reason why it is not extended to precessing cases?

**Comment by ahnitz** [comment]
@haris-mk It could be modified to handle precessing. You'd have to handle the plus / cross terms separately then and sample directly of the coalescence phase instead of the simple marginalization. A version of the model that did this would be a reasonable addition to pycbc if somewhat were interested in adding it.

**Comment by ahnitz** [comment]
@ahnitz Yes, that may be an issue. I only checked carefully that the sky location / inclination was recovered self-consistently, I don't remember about the polarization angle, so it's possible it will be essentially redefined (as you can transform plus to cross terms in the  non-precessing case ans used here with an offset). Definitely worth fixing.

**Comment by ahnitz** [comment]
@haris-mk I've looked into this a bit more. You are right. In my testing, I find I can transform the polarization angle to "fix" this, but it would mean that if you actually wanted to measure polarization angle you'd get an incorrect result. It gives correct results only if you sample over the full range or marginalize it out. 

Will be addressed in https://github.com/gwastro/pycbc/pull/3577

**Comment by ahnitz** [comment]
@haris-mk This was fixed a while back by #3577. Thank you for reporting!
