### ISSUE TITLE
PyCBC Live test: generate PTA files and use a PTA-based ranking

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#3580]
The current example/test of PyCBC Live uses a simplistic `--ranking-statistic quadsum` which is not what was used in production during O3. Modify the example to create minimal PTA histogram files and use a ranking that includes the PTA term, such as `phasetd`.

Requires fixing #3584.

**Comment by dentt** [comment]
@titodalcanton it's not totally clear from this description what the work required here is. Is 'implementing the required ranking' (as oppose to using it) part of this issue?

**Comment by titodalcanton** [comment]
@dentt yeah, it was confusing. I opened a separate issue for the required ranking, and updated the above description.

**Comment by titodalcanton** [comment]
It would make a lot of sense for a single PR to address both #3584 and #3580, by the way.
