### ISSUE TITLE
Speed up or parallelize `pycbc_fit_sngls_over_multiparam`

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#3585]
`pycbc_fit_sngls_over_multiparam` seems to involve N^2 operations, with N the number of templates in the bank. With large template banks, `fit_sngls_over_multiparam` jobs can become bottlenecks for the all-sky coincident search workflow. Can the operation be parallelized across 10 or 100 jobs and the results merged, like we do for optimal SNRs?

**Comment by ahnitz** [comment]
A little more info is needed on how much speed-up (wall-time) is desired and what kind of parameters are used. In general, I think it's better to optimize the code than to try to parallelize it. 

It could be sped up by simply creating and pre-assigning templates to 'buckets' based on a sorted grid. This would make the operation count a lot closer to optimal for at least the 2-d case. I'm not sure about 3-d, but it would be certainly faster if one dimension is much longer than the others.

**Comment by GarethDaviesGW** [comment]
I'm not sure whether parallelization or buckets could even work here, as the information for each template is used for all nearby templates without any hard borders

Unless we had 'fuzzy' buckets/parallelization? Where some templates are in more than one job/buckets, but that may just be moving the problem

**Comment by tdent** [comment]
well, if there are some dimensions that are many smoothing-lengths, you can make bins that are 1 smoothing length and then you need to calculate distances over at most 2 bins at once

**Comment by titodalcanton** [comment]
@GarethDaviesGW it seems to me that this for loop is embarassingly parallel,
```python
else:
    for i in range(len(nabove)):
        dsq = dist(i, rang)
```
but I agree with Alex on optimization.

**Comment by titodalcanton** [comment]
> A little more info is needed on how much speed-up (wall-time) is desired and what kind of parameters are used.

The jobs that completed from the workflow I am referring to took about a day and used 3 fitting parameters. Another one, still running but hopefully close to completion, has accumulated a comparable amount of CPU time so far. So having them complete in a couple hours instead would help the workflow a lot.

**Comment by tdent** [comment]
Is this still desired?

**Comment by GarethCabournDavies** [comment]
I think it is, as the distance calculation is still done , if you have time/someone to add this that would be great!

**Comment by GarethCabournDavies** [comment]
That makes sense to me, Though I think it would have to be modified for the different types of smoothing. (the "closest N templates" is particularly confusing me right now

Does it have to be in 1D actually? It should be the case in all dimensions

**Comment by GarethCabournDavies** [comment]
I think we can close this due to #4374
