### ISSUE TITLE
single_template inference model has a hardcoded sample rate

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3671]
Continuing in the series of "things that don't work well with LISA" (I think this is one thing I noticed last year, but didn't say anything about, and is therefore still an issue). The "single_template" model in pycbc_inference hardcodes a sample rate of 32kHz (and will upsample waveforms to this when it initializes). If running with days (or weeks/months/years) long signals with desired sample rates of 1 / 15., this quickly breaks. 

Is there a reason this doesn't use the sample rate of the incoming data? I think that's what gaussian_noise model does?

**Comment by ahnitz** [comment]
@spxiwh It's not hardcoded, it simply has a default. You can set it to what you want.

**Comment by ahnitz** [comment]
In your config file you set
```
[model]
sample_rate = 8192
```

**Comment by ahnitz** [comment]
The example also shows doing this, though I guess the comment doesn't make it clear that you could choose a  *lower* number. https://pycbc.org/pycbc/latest/html/inference/examples/single.html

**Comment by ahnitz** [comment]
@spxiwh It wouldn't normally work well to use *exactly* the sample rate of the data, as usually you have much better timing resolution that that. The sample rate here needs to be high enough that the likelihood values of neighboring time points are close enough that you don't care that those are the only times that will be sampled. 

I guess one could have a kind of rule of thumb as a default. Something simple like SR * 16 or maybe based on an approximation to the timing uncertainty ala Fairhurst-style? Is that what you'd prefer? If so, yeah, that sounds like a good improvement if someone would like to put in a PR.

**Comment by ahnitz** [comment]
@spxiwh To be completely clear the sample rate is is the resolution that time of arrival in each detector is measured at. This is completely different than say the 'gaussian_noise' model which allows sub-sample timing resolution. The single-template model does not allow sub-sample timing resolution.

**Comment by spxiwh** [comment]
@ahnitz Thanks for that. We had added the sample rate (twice) already (once for fake-strain-sample-rate, once for sample-rate, though I suspect the former is not needed), but had not noticed that it can be specified here as well.

What is the design motivation for requiring the user to choose a higher sample rate to get the time more accurately rather than using (https://github.com/gwastro/pycbc/blob/master/pycbc/filter/matchedfilter.py#L1439) a very fast interpolation routine? I guess the interpolation would be a *little* slower, but should be utterly negligible compared to the `htf = (fp * ip + 1.0j * fc * ic) / p['distance']` line. (Indeed as that calculation would be *faster* at lower sample rates, this would speed things up *and* provide better time resolution). ... Of course the user still has to choose a sane sample rate for data generation, but then that's in line with the gaussian_noise model.

**Comment by ahnitz** [comment]
@spxiwh 

The operation you pointed to does not change in cost with sample rate. In fact, you can choose as high as you like currently and the compuational cost is completely unaffected during sampling. The only thing that changes is the upfront pre-computation and the memory needed to store it. 

You ask why not do some kind of interpolation? You could, but it only adds complexity where there needed to be none, once you have the SNR time series pre-calculated anyway. The function you point to wouldn't be appropriate as remember you aren't trying to just find a peak, you are trying to find the likelihood for some arbitrary precision time.

**Comment by spxiwh** [comment]
@ahnitz Okay, I did misread what `ip` and `ic` were on that line (not the SNR timeseries). While it is true that the function in question does peak finding, the method could be easily extended to allow `self.sh[ifo].at_time(p['tc'] + dt)` to do a basic sub-sample interpolation (optionally). (But I'll close this as the original issue is not true)
