### ISSUE TITLE
Error for waveform plugin

### ISSUE THREAD

**Issue by yi-fan-wang** [gwastro/pycbc#3750]
I suspect this [line]( https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L951.) has an error. This function converts those Fourier domain waveforms with `_filter_time_lengths` to a time domain one. 

I tried to add a new FD waveform as per http://pycbc.org/pycbc/latest/html/waveform_plugin.html with a `setup.py` with a _filter_time_length. But the new waveform's _filter_time_length seems to not be recognized by [here]( https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L951.). `pycbc.waveform.waveform._filter_time_length` does include my new waveform's length. So I suspect the above line only include those length estimation listed in the pycbc/waveform/waveform.py and not those new waveforms added through plugin.

**Comment by ahnitz** [comment]
@yi-fan-wang it is probably an order of operations issue (or at least that's my guess). When is the plugin loaded vs this part of the code? In any case, can I assign this to you to fix? I won't be able to look at addressing this in the short term.

**Comment by yi-fan-wang** [comment]
@ahnitz Sure, I'll try to fix it.
