### ISSUE TITLE
Issue with gating in pycbc_multi_inspiral

### ISSUE THREAD

**Issue by jakeb245** [gwastro/pycbc#3751]
On the current version of pycbc (1.18.1), there is an issue within the gating options of pycbc_multi_inspiral. The code that does gating has been updated to require a new input for the gating method ([link here](https://github.com/gwastro/pycbc/blob/638cd48d0174a3dd8673882aa91f4c2e8ec8e0b2/pycbc/strain/strain.py#L336)). This is implemented for the single detector strain option group, but not the multi detector that pycbc_multi_inspiral uses.

[This is the option implemented for single detector](https://github.com/gwastro/pycbc/blob/638cd48d0174a3dd8673882aa91f4c2e8ec8e0b2/pycbc/strain/strain.py#L580) and [this is where it would likely be implemented for multi detector](https://github.com/gwastro/pycbc/blob/638cd48d0174a3dd8673882aa91f4c2e8ec8e0b2/pycbc/strain/strain.py#L799).

Because of this, using gating causes the program to crash, with the error message saying that this gating method option is required. It also crashes if you try to run the code with the gating method option, saying that the argument is unrecognized. It may be as simple as adding the option to the multi detector option group.

**Comment by spxiwh** [comment]
@jakeb245 Thanks for this. This a known pain with the input options used here. @ahnitz and I discussed this while implementing the multi-detector option interface (it was implemented for pycbc_multi_inspiral, but is now used most heavily in the inference code) but didn't find a better solution than repeating all of these options. This does lead to issues like this where an option gets added in one place, and not both. We try and look our for this happening, but obviously it remains a problem.

The resolution you propose of just adding this in the place you indicate for multi detector is the right solution. Do you want to go ahead and propose that as a PR and assign to me?

**Comment by jakeb245** [comment]
@spxiwh Sure, I'll go ahead and do that

**Comment by titodalcanton** [comment]
Fixed by #3752.
