### ISSUE TITLE
Duplicate module?

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#3779]
@veronica-villa @tdent Do we need separate modules in https://github.com/gwastro/pycbc/blob/master/pycbc/mchirp_area.py and https://github.com/gwastro/pycbc/blob/master/pycbc/mchirp_area_improved.py ? Can these be combined into one if both are needed, or one of them removed if no longer needed?

**Comment by tdent** [comment]
Yes, if the new module is reviewed to produce the same numbers as the old then the plan is to remove the old and rename the new one
