### ISSUE TITLE
Bug in pycbc_inference_plot_posterior

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3786]
The conditional here:

https://github.com/gwastro/pycbc/blob/master/pycbc/results/scatter_histograms.py#L598

is buggy. If there are 2 parameters and `--plot-marginal` is not given then only one image is created in the corner plot and the length of `width_ratios` and `height_ratios` must be 1.

This should be reproducible with any inference output with something like:

```
pycbc_inference_plot_posterior --plot-scatter --input-file test.hdf --output-file test.png --z-arg snr --verbose --parameters "mass1" "mass2"```

Just need exactly 2 parameters and no `--plot-marginal`. Not sure what exactly this line is doing, so unsure how to suggest a fix (other than just delete the conditional).

**Comment by GarethCabournDavies** [comment]
Fixed in #4695
