### ISSUE TITLE
Bug in pycbc_add_statmap(?)

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3792]
In a test workflow I'm seeing a problem as the number of triggers found here:

https://github.com/gwastro/pycbc/blob/master/bin/all_sky_search/pycbc_add_statmap#L196

is not the same as the number of triggers here:

https://github.com/gwastro/pycbc/blob/master/bin/all_sky_search/pycbc_add_statmap#L213

when searching for stat.

The difference seems to be that the `foreground/ifar` dataset is not present for triple coincident triggers at all (and combining this column is then not meaningful). Have I just plucked a version of code from between changes? I'd be surprised that no-one else noticed this??

**Comment by spxiwh** [comment]
Ah wait, it looks like this was due to me using a partial output file from a failed run.

**Comment by ahnitz** [comment]
@spxiwh I'm not sure yet what you mean. The first line should be before clustering, and the second should give you the indices afterwards, so by definition it should be smaller or as large. Most likely note the same.

**Comment by spxiwh** [comment]
In my example `f['foreground/stat']` and `f['foreground/ifar']` were not giving the same number of triggers.
