### ISSUE TITLE
cpnest sampler is broken

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3797]
I was playing around with `cpnest` and hit a problem with this line https://github.com/gwastro/pycbc/blob/master/pycbc/inference/sampler/cpnest.py#L230 

```
  File "/nfshome/store02/users/ian.harry/virtualenvs/pycbc_python3_dopp/lib/python3.6/site-packages/pycbc/inference/sampler/cpnest.py", line 232, in new_point
    [point[p] for p in self.model.sampling_params])
TypeError: Argument 'd' has incorrect type (expected array.array, got list)
Traceback (most recent call last):
```

Looking over the cpnest source code this function is actually a direct call to a `cdef`ed function in Cython where all inputs must be certain types. Strangely it wants the input to be an `array.array` object, which I've never used before but seems a "not as good as numpy array, array". To fix this the second argument becomes:
```
array.array('d', [point[p] for p in self.model.sampling_params]) # The 'd' I think is the type declaration, double??
```

However, I'm not proposing this as a pull request at the moment because I don't know what version of cpnest this changed in, which may set a specific version to be required. Who is responsible for cpnest to assign this to?

**Comment by ahnitz** [comment]
@spxiwh You can assign to me if you like. This is a case where we should re-enable the sampler test for cpnest. (it was not enabled initially as cpnest doesn't work in python2 so was a pain to handle when we were still supporting that). I think we can just advance to the most recent cpnest release. They do not appear to occur that often.

**Comment by ahnitz** [comment]
i.e. update here to include the cpnest minimal example https://github.com/gwastro/pycbc/blob/master/examples/inference/samplers/run.sh

**Comment by ahnitz** [comment]
This has been fixed for some time.
