### ISSUE TITLE
pycbc_make_faithsim uses the old glue workflow modules

### ISSUE THREAD

**Issue by duncan-brown** [gwastro/pycbc#385]
The workflow generator pycbc_make_banksim uses the deprecated glue workflow modules to build DAGs directly. It should be re-written to use the workflow construction modules in PyCBC to write a DAX.

**Comment by duncan-brown** [comment]
@spxiwh can this be closed now?

**Comment by spxiwh** [comment]
No. pycbc_make_banksim (and pycbc_make_faithsim) are still using glue.workflow.

**Comment by duncan-brown** [comment]
@spxiwh can this be closed?

**Comment by spxiwh** [comment]
No, because pycbc_make_faithsim hasn't been rewritten yet. I'll change the title though.

**Comment by titodalcanton** [comment]
Fixed by #4163.
