### ISSUE TITLE
Can't use negative values for --loudest-keep-values in pycbc_coinc_findtrigs

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#3876]
One can't do the following 

```
pycbc_coinc_findtrigs --loudest-keep-values 10:10 0:10 -5:10
```
The following also does not work
```
pycbc_coinc_findtrigs --loudest-keep-values "10:10 0:10 -5:10"
pycbc_coinc_findtrigs --loudest-keep-values "10:10" "0:10" "-5:10"
```
In the former case it (naturally) gets treated as a single argument. In the latter, you get an error that argparse isn't expecting an option -5:10. The quotes don't appear to do anything. 

See related problem https://bugs.python.org/issue9334

Thoughts are to allow a token stand in place of '-' or to revierse the order of the threshold vs decimation factor (which does work). The issue seems to be anytime there is a leading hyphon irrespective of any earlier quotes.

**Comment by tdent** [comment]
It would be nice to have a strategy that worked in general for negative number option values. Though not sure how to implement that

**Comment by tdent** [comment]
For example would the following syntax work
`--loudest-keep-values [10:10,0:10,-5:10] `
the brackets allowing even the first value to be negative

**Comment by GarethCabournDavies** [comment]
That's weird, as the job didn't fail on a test that I did to test the negative numbers in these options

**Comment by ahnitz** [comment]
@GarethCabournDavies If its the test in the search workflow, you didn't put the options in correctly, so they were never actually sent to any coinc jobs.If by hand, then I think you should have seen an error.

**Comment by ahnitz** [comment]
@GarethCabournDavies See change in #3877
