### ISSUE TITLE
Inconsistent timing in pycbc_create_injections

### ISSUE THREAD

**Issue by MarlinSchaefer** [gwastro/pycbc#3893]
When generating more than 4000 injection parameters through `pycbc_create_injections` and using the options `--time-step` and `--time-window` without using `--ninjections`, some injection times `tc` are separated by less than the time window specified by the option.

I think this is caused by generating the injections in blocks of 4000. When a new block is started it is not enforced that the last sample of the prior block and the first sample of the new block are separated by the given amount of time. (See lines starting [here](https://github.com/gwastro/pycbc/blob/master/bin/pycbc_create_injections#L238))

I'll post a PR with a suggestion to resolve this issue.

**Comment by ahnitz** [comment]
Fixed by #3894
