### ISSUE TITLE
Analytical PSDs do not warn the user that they are going beyond the correct range

### ISSUE THREAD

**Issue by jacopok** [gwastro/pycbc#3938]
When generating an analytical PSD, for example with `pycbc.psd.from_string`, 
the frequency bounds are not checked against the file the PSD comes from, 
and `pycbc` (or `lalsimulation`?) happily interpolates beyond the correct range.

I came across this with the ET-D PSD for Einstein Telescope, 
which I believe comes from the file 
https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalsimulation/lib/LIGO-P1600143-v18-ET_D.txt
where it is sampled from 5 to 5000Hz.
Beyond this, some sort of interpolation is used leading to wildly incorrect results:

```
import pycbc.psd
import matplotlib.pyplot as plt

pycbc_psd = pycbc.psd.from_string(
    'EinsteinTelescopeP1600143', 
    length=int(1e7), 
    delta_f = 0.001, 
    low_freq_cutoff = .001
    )

plt.loglog(pycbc_psd.sample_frequencies, pycbc_psd, label='Should be ET-D')
plt.axvline(5, label='Actual correct range', c='black', ls=':')
plt.axvline(5000, c='black', ls=':')
plt.legend()
plt.xlabel('Frequency [Hz]')
plt.ylabel('PSD')
```
![et-d-incorrect](https://user-images.githubusercontent.com/11020774/154726456-25659e52-1a1f-4e03-b03f-a6682b06e73d.png)

For reference, the ET-D PSD at 1Hz is estimated to be [~10 orders of magnitude larger than this](http://www.et-gw.eu/index.php/etsensitivities)! 

The issue is that the user has no way to know in which range the PSD can be trusted; the ideal behaviour would be to throw an error if the bounds exceed the "correct" range.
Looking at the code which implements this it is not clear to me how to go about it, but nevertheless, this is an important issue.

**Comment by titodalcanton** [comment]
@jacopok analytical PSDs in PyCBC are taken verbatim from lalsimulation: each model is simply mapped directly to a call to the corresponding lalsimulation PSD function (there is one exception, the `flat_unity` PSD, but I guess you are not concerned with that here). The interpolation is done in lalsimulation, in a way completely transparent (or opaque, if you want) to PyCBC. Then PyCBC can only assume that lalsimulation is providing a meaningful model. The check you suggest sounds useful, but since the underlying data files are in lalsimulation, the check should be implemented there.

**Comment by jacopok** [comment]
I saw that the PSDs come verbatim from lalsimulation and I am going to raise the issue there as well; I hoped that a check could be performed here too but if that is not feasible feel free to close this, of course.

**Comment by jacopok** [comment]
Or, perhaps, if this value can be retrieved it could just be a `logging.warning` raised by `pycbc` when needed...

The value can probably be retrieved, since `lalsimulation` knows about it (it is the `flow` parameter in code such as [this](https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/group___l_a_l_sim_noise_p_s_d__c.html#gac3aacf37202881604f39c1b4867b69cb))

**Comment by spxiwh** [comment]
@jacopok The flow parameter in the function you point to is *not* the lowest valid frequency in the PSD txt file, but the lowest frequency the user wants to generate. The lalsimulation interface *does not* expose the lowest valid frequency as far as I can tell. This is all handled in here (https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/_l_a_l_sim_noise_p_s_d_8c_source.html#l01041).

I *think* that the code uses a linear fit to the first and second points in the PSD file to extrapolate frequency values *below* that in the file, but the code does not raise any sort of warning that it is doing that, or allow for the code to error in this case.

I do think that this means that any changes here should live at the lalsimulation level, and PyCBC should just call the interface and not try to second-guess it.

Perhaps the more direct problem here is that the ET-D PSD in lalsimulation is only valid to 5Hz, yet people often talk about ET having sensitivity down to 1Hz. I'm not sure the ET-D PSD (does this originate with the ET design document from 10 years ago???) is necessarily the most current knowledge here either. I note that PyCBC does let you provide your own ASCII PSD/ASD files to generate a PSD from. I think this PyCBC code does check if it is interpolating outside the limits of the text file provided, so I would suggest using this if doing ET/Cosmic Explorer studies!

.... I'll leave this issue open for now in case you disagree, but if someone views this some weeks from now and there is no further conversation, then please close!

**Comment by jacopok** [comment]
I see, I misunderstood the `flow` parameter in LAL, in which case I completely agree: since the minimum frequency is not exposed, changes can only happen in LAL --- I've contacted the developers there to see whether this can be addressed. 

Regarding the ET PSD specifically, a wider one is available (http://www.et-gw.eu/index.php/etsensitivities, which brings one to [this download page](https://apps.et-gw.eu/tds/?content=3&r=14065)) going down to 1Hz --- I'm not sure since when this is the case, but the one in LAL could be updated for sure.

![ET-PSD-comparison](https://user-images.githubusercontent.com/11020774/155186521-bfa9459c-7bdd-4910-ba8e-6fa42c9217fc.png)

I think this issue could _almost_ be closed, then, with one possibility left: would you accept a pull request to modify the [docs](https://pycbc.org/pycbc/latest/html/psd.html) with a brief outline of this potential problem, to be kept until LAL changes something?

P.S. 
Perhaps that page could be referenced [here](https://pycbc.org/pycbc/latest/html/pycbc.psd.html)? This is the first page to come up when one searches for "psd" on the docs site.
This is somewhat off-topic, I know, but it seemed relevant in view of helping new users who may be looking for information about this.

**Comment by spxiwh** [comment]
Always happy to accept improvements to documentation :-). It is probably worth a mention of this in the "Generating an Analytic PSD from lalsimulation" section. The https://pycbc.org/pycbc/latest/html/pycbc.psd.html page is autogenerated and just contains all of the function/module documentation in the code. However, I guess the first thing that appears is the text here:
https://github.com/gwastro/pycbc/blob/master/pycbc/psd/analytical.py#L17
and we'd be happy to accept a PR that extends this description as needed!
