### ISSUE TITLE
pycbc.psd.from_numpy_arrays fails

### ISSUE THREAD

**Issue by MarlinSchaefer** [gwastro/pycbc#3952]
The following code fails with my PyCBC installs
```python
from pycbc.psd import aLIGOZeroDetHighPower, from_numpy_arrays

psd = aLIGOZeroDetHighPower(1024, 1, low_freq_cutoff=0)
psd = from_numpy_arrays(psd.sample_frequencies, psd, 2048, 0.5, 15)
```
and gives the error message
```
/home/marlin/environments/pycbc3/lib/python3.6/site-packages/pycbc/types/array.py:213: RuntimeWarning: divide by zero encountered in log
  ret = getattr(ufunc, method)(*inputs, **kwargs)
Traceback (most recent call last):
  File "flow_issue.py", line 4, in <module>
    psd = from_numpy_arrays(psd.sample_frequencies, psd, 2048, 0.5, 15)
  File "/home/marlin/environments/pycbc3/lib/python3.6/site-packages/pycbc/psd/read.py", line 72, in from_numpy_arrays
    psd[kmin:] =  numpy.exp(psd_interp(vals))
  File "/home/marlin/environments/pycbc3/lib/python3.6/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/home/marlin/environments/pycbc3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 663, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/marlin/environments/pycbc3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 695, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range.
```

I think the reason for this failure is the following line [https://github.com/gwastro/pycbc/blob/master/pycbc/psd/read.py#L68](https://github.com/gwastro/pycbc/blob/master/pycbc/psd/read.py#L68), where the `int` call always reduces the low frequency cutoff to be below the available frequency data. I would suggest using
`kmin = int(numpy.ceil(low_freq_cutoff / delta_f))`
instead.

**Comment by WuShichao** [comment]
@MarlinSchaefer I have encounter same problem, you can see here https://github.com/gwastro/pycbc/pull/3935

**Comment by MarlinSchaefer** [comment]
Thanks for pointing that out. I hadn't checked carefully enough. I guess this issue can be closed.

**Comment by MarlinSchaefer** [comment]
The minimal working example I posted above is ill-posed, as it requests a higher frequency than is available in the original data. The correct example would be
```python
from pycbc.psd import aLIGOZeroDetHighPower, from_numpy_arrays

psd = aLIGOZeroDetHighPower(1024, 1, low_freq_cutoff=0)
psd = from_numpy_arrays(psd.sample_frequencies, psd, 2047, 0.5, 15)
```
which executes without error. However, I experienced this error in a different context, where explicitly the low-frequency cutoff was the problem. I'll try to come up with a minimal examples that demonstrates the issue.

**Comment by WuShichao** [comment]
@MarlinSchaefer I have the example for  the low-frequency cutoff issue:
```
fs = 4096
delta_f = 1.0/8
length = int(fs/2/delta_f) + 1
filename = "/mnt/d/on-source_psd_correction/detector_network/ASD/cosmic_explorer.txt"
det_psd = from_txt(filename, length, delta_f, 5.000000000000000888e+00, is_asd_file=True)
print(det_psd.sample_frequencies)
```
You need to download this https://dcc.cosmicexplorer.org/CE-T2000017/public

**Comment by MarlinSchaefer** [comment]
@WuShichao Okay, great. You can also reproduce the error from PyCBC itself using this code:
```python
from pycbc.psd import aLIGOZeroDetHighPower, from_numpy_arrays

df = 0.062372468402619154
psd = aLIGOZeroDetHighPower(1024, 1, low_freq_cutoff=15)
psd = from_numpy_arrays(psd.sample_frequencies, psd, 16384, df, 19)
```

**Comment by ahnitz** [comment]
@MarlinSchaefer Is this sufficiently addressed now?

**Comment by WuShichao** [comment]
@ahnitz I have tested all the examples in this issue, and Marlin has tested too https://github.com/gwastro/pycbc/pull/3935#pullrequestreview-910131175

**Comment by ahnitz** [comment]
@MarlinSchaefer Assuming this is now resolved, I'll close this issue. Please re-open if this is mistaken.
