### ISSUE TITLE
Offline workflow expects optimal_snr_merge jobs to produce an xml file

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#3956]
As in the title. The all-sky search is currently broken as it is necessary to merge optimal snr files, but there is no executable to do that now that they are hdf, also the workflow generation currently seems to assume that the result of doing so will be an xml file.

**Comment by tdent** [comment]
I think we will be able to put together a merge_optimal_snr_hdf executable, but we may need guidance or help on necessary changes to the workflow.

**Comment by spxiwh** [comment]
The workflow changes should be pretty minor, as we can just repurpose most of what's there. It doesn't make sense to do that until the executable exists though, I can help from there!

**Comment by titodalcanton** [comment]
It seems worth having a more general `pycbc_merge_injections` script which just merges injection tables, whatever they contain - including optimal SNRs.

**Comment by titodalcanton** [comment]
Hehe, something like this maybe? https://github.com/gwastro/pycbc/blob/master/bin/pycbc_merge_inj_hdf

**Comment by tdent** [comment]
Maybe, I just hope my student doesn't wast too much time duplicating it.  Seriously, there seems to be a communication problem here ...

**Comment by tdent** [comment]
So the remaining work is to clean up the merge executable inputs/outputs and options and hdfinjfind inputs within the workflow module and/or workflow generator

**Comment by tdent** [comment]
@spxiwh Since a working executable now exists, this is where you would start to step in on the workflow side ?

**Comment by ahnitz** [comment]
@tdent You might want to ask @dethodav if they had tried this out in a workflow already. I seem to recall that they might have tested it, but perhaps it wasn't in full workflow configuration.
