### ISSUE TITLE
Adjust coalescence time in WaveformGenerator

### ISSUE THREAD

**Issue by LAujust** [gwastro/pycbc#3959]
I am using fisher information matrix to evaluate detection ability, where I need to get difference of response with respect to params including  `t_c` (coalescence time). However, I found that I have failed to adjust `t_c` in `get_fd_waveform` for `t_c` is not a input parm.
So I would really appreciate it if someone could offer me a helpful solution.

**Comment by yi-fan-wang** [comment]
Hi, 
get_fd_waveform only generates waveform in the frequency domain so there is no time parameter. Use get_td_waveform for time domain waveforms. See section "Generating one waveform in multiple detectors" in http://pycbc.org/pycbc/latest/html/waveform.html for an example to generate waveforms in the time domain for H1, L1, and V1 detectors. I think the "end_time" there is what you're looking for.

**Comment by LAujust** [comment]
Thanks a lot! It really helps!

**Comment by ahnitz** [comment]
@LAujust If you are doing a fisher matrix calculation, presumably you are doing some inner products. If so, you will need to actually time shift the signal within some fixed vector representation. To do that you probably want to use the 'cyclic_time_shift' method of the time series which will shift the data points in the vector by subsample level precission. 

Note that it updates the time stamps too, so it doesn't really change what parts of a signal are associated with which time, but if you do a vector inner product you can simple set the start times the same after applying the shift and do your inner product. 

The code that @yi-fan-wang pointed you to will project signals at different times into a specific detector frame, but may not produce signals that all have the same start time of the vector. So, for example, if you were to plot them using the associated time stamps, they would be shifted correctly, but their data vector representation doesn't necessarily correspond to the same 'window' (i.e. start time / end time boundaries).
