### ISSUE TITLE
O4 Sensitivity

### ISSUE THREAD

**Issue by LAujust** [gwastro/pycbc#4051]
I need use LIGO/Virgo O4 sensitivity in my work, but not finding noise data but figure. And psd in PYCBC only contains O3 and A+. Where can I get O4 psd data?

**Comment by titodalcanton** [comment]
@LAujust we do indeed have O4 noise models in PyCBC, for example `aLIGOAdVO4T1800545` which should give you the Advanced Virgo O4 sensitivity described in the [observing scenarios paper](https://link.springer.com/article/10.1007/s41114-020-00026-9) (the `aLIGO` part is a typo which I have been trying to get fixed). Unfortunately it is not trivial to know which noise model function corresponds to what document; the best place is probably a comment in the LALSimulation source code itself, which is where the analytic models in PyCBC are taken from. For the function I mentioned, this would be [here](https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/group___l_a_l_sim_noise_p_s_d__c.html#ga34dbba2900459a7b9295e0e5d1d8a3eb).

**Comment by titodalcanton** [comment]
I am closing this, feel free to reopen if you realize my answer is not sufficient.
