### ISSUE TITLE
PyCBC + PyTorch = segfault

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4052]
If one tries to install PyCBC alongside PyTorch (very common ML module), it causes breakages. For things like PyTorch, you really need conda, so you can do something like:

```
conda create -n TESTING python=3.9
conda activate TESTING
conda install -c conda-forge pycbc # PyCBC runs at this point
conda install -c conda-forge pytorch
```

then run something that calls into the FFT module:

```
import numpy as np
from pycbc import types
from pycbc import fft
inarr = types.Array(np.ones([64], dtype=np.complex64))
outarr = types.Array(np.zeros([64], dtype=np.complex64))
fft.fft(inarr, outarr)
print(outarr)
```

and the code segfaults. It runs fine before the pytorch install. The segfault occurs whenever a call to FFTW is made, if one uses MKL instead the code runs fine, but as `conda install pycbc` brings in fftw, it's hard to disable it (without a hack!) 

We have seen a similar issue (actually I think the same issue) when doing some testing with intel-compiled python on CIT, but this is an easier way to reproduce this. The common element seems to be the introduction of MKL-compiled binaries (BLAS et al.) when installing pytorch. I just don't know why bringing in MKL-accelerated versions of libraries that FFTW doesn't use would break FFTW?? Perhaps because numpy arrays are in play and numpy does depend on BLAS etc.???

... I have a suspicion that others have hit this though, because I have heard complaints that "pycbc doesn't build/work", without something I could reproduce.

**Comment by ahnitz** [comment]
Can you verify if this occurs in a virtualenv? That might help pinpoint a
difference as we use this combination of software  for the ml MDC and don't
run into this problem.

**Comment by ahnitz** [comment]
And if you then install 

```
conda install -c conda-forge libblas=3.9.0=15_linux64_openblas
```

The segfault goes away

**Comment by ahnitz** [comment]
@spxiwh I can confirm your suspicion, though I'm not closer to understanding why. You can remove the error by changing a single rpath link so that numpy doesn't point to the mkl version of cbls. 

```
(env) [ahnitz@fedora core]$ ldd _multiarray_umath.cpython-39-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffead7c5000)
	libcblas.so.3 => /home/ahnitz/.conda/envs/TESTING/lib/python3.9/site-packages/numpy/core/./../../../../libcblas.so.3 (0x00007f1d6918e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1d6901e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1d68e53000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1d69ec9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f1d68e4c000)
```

I used chrpath to change the rpath of the so to point to the openblas version and then the test you posted works fine. If I change back to the mkl library, it fails.

**Comment by ahnitz** [comment]
@spxiwh Ok, here's something. I've reduced the failing case to one that *only* requires numpy and fftw and no pycbc at all. 
```
import numpy
import ctypes
from ctypes.util import find_library

fullpath = find_library('fftw3f')
print(fullpath)
float_lib =  ctypes.CDLL(fullpath)

ip = numpy.zeros(2**10, dtype=numpy.complex64)
op = numpy.zeros(2**10, dtype=numpy.complex64)

f = float_lib.fftwf_plan_dft_1d
f.restype = ctypes.c_void_p
f.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
              ctypes.c_int, ctypes.c_int]
theplan = f(2*19, ip.ctypes.data, op.ctypes.data, 1, 0)
destroy = float_lib.fftwf_destroy_plan
destroy.argtypes = [ctypes.c_void_p]
destroy(theplan)
```

This segfaults in the same way you've observed, and if MKL is removed so that numpy no longer links against it, then this succeeds.  :shrug: :cry: :confused:

**Comment by ahnitz** [comment]
@spxiwh As probably far as I get tonight, but here's something even simpler that even removes direct useage of numpy arrays (i.e. rules out somehow numpy giving bad pointers to the fftw functions). 

If you uncomment the *single* line that imports numpy, then it will segfault. This occurs even though no numpy function is called. I think this indicates that something is settings some kind of global state. If you alternatively 
change the library that numpy links to (i.e. changing the libcblas.so.3 alias from libmkl_rt.so to the openblas library), it will stop failing. 

I would bet hard that somehow if libmkl_rt.so is loaded before fftw, then something has changed in some kind of global state that causes fftw to fail.  

@josh-willis Any ideas here?

```
#import numpy     # uncomment me to segfault FFTW!!!!!!!!!!
import array, ctypes
from ctypes.util import find_library

fullpath = find_library('fftw3f')
float_lib =  ctypes.CDLL(fullpath)

size = 2**5
ia = array.array('f', [1.1] * (size * 2))
oa = array.array('f', [1.1] * (size * 2))
iptr = ia.buffer_info()[0]
optr = oa.buffer_info()[0]

f = float_lib.fftwf_plan_dft_1d
f.restype = ctypes.c_void_p
f.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
              ctypes.c_int, ctypes.c_int]
theplan = f(size, iptr, optr, 1, 0)
destroy = float_lib.fftwf_destroy_plan
destroy.argtypes = [ctypes.c_void_p]
destroy(theplan)
```

**Comment by ahnitz** [comment]
@spxiwh @josh-willis Ok, nvm, one more update. I got rid of numpy entirely. It does have to do with if MKL is imported first (or if any mkl function is run it would seem). For example, the following. 

```
import array, ctypes
from ctypes.util import find_library

for lib in ['libmkl_rt.so', 'fftw3f']:    # This one segfaults
#for lib in ['fftw3f', 'libmkl_rt.so']:   # This one doesn't segfault!
    fullpath = find_library(lib)
    float_lib =  ctypes.CDLL(fullpath)
    print(fullpath)
    size = 2**5
    ia = array.array('f', [1.1] * (size * 2))
    oa = array.array('f', [1.1] * (size * 2))
    iptr = ia.buffer_info()[0]
    optr = oa.buffer_info()[0]

    f = float_lib.fftwf_plan_dft_1d
    f.restype = ctypes.c_void_p
    f.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
                  ctypes.c_int, ctypes.c_int]
    theplan = f(size, iptr, optr, 1, 0)
    destroy = float_lib.fftwf_destroy_plan
    destroy.argtypes = [ctypes.c_void_p]
    destroy(theplan)
 ```

**Comment by spxiwh** [comment]
I can get the example where "removing import numpy causes fail/success" to work, by ensuring that we call+use FFTW3 before numpy is imported:

```
import array, ctypes
from ctypes.util import find_library

fullpath = find_library('fftw3f')
float_lib =  ctypes.CDLL(fullpath)
print(fullpath)
#if lib == 'libmkl_rt.so':
#    continue
size = 2**5
ia = array.array('f', [1.1] * (size * 2))
oa = array.array('f', [1.1] * (size * 2))
iptr = ia.buffer_info()[0]
optr = oa.buffer_info()[0]
f = float_lib.fftwf_plan_dft_1d
f.restype = ctypes.c_void_p
f.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
              ctypes.c_int, ctypes.c_int]
theplan = f(size, iptr, optr, 1, 0)
destroy = float_lib.fftwf_destroy_plan
destroy.argtypes = [ctypes.c_void_p]
destroy(theplan)

import numpy # Now importing numpy doesn't segfault

for lib in ['fftw3f', 'libmkl_rt.so', 'fftw3f']:   
    fullpath = find_library(lib)
    float_lib =  ctypes.CDLL(fullpath)
    print(fullpath)
    #if lib == 'libmkl_rt.so':
    #    continue
    size = 2**5
    ia = array.array('f', [1.1] * (size * 2))
    oa = array.array('f', [1.1] * (size * 2))
    iptr = ia.buffer_info()[0]
    optr = oa.buffer_info()[0]

    f = float_lib.fftwf_plan_dft_1d
    print(f)
    f.restype = ctypes.c_void_p
    f.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
                  ctypes.c_int, ctypes.c_int]
    theplan = f(size, iptr, optr, 1, 0)
    destroy = float_lib.fftwf_destroy_plan
    destroy.argtypes = [ctypes.c_void_p]
    print(theplan)
    destroy(theplan)
    print(theplan)
```

So I suspect some sort of precedence thing going on(?) The FFTW3 function *names* are defined within MKL, so it seems that we need to import/use the FFTW3 ones before touching MKL (difficult though as import numpy is likely to appear before any PYCBC import in many cases)?? ... I guess an alternative would be to use the wrapper functions in MKL if MKL is there, but then that seems to boil down to "disable FFTW if MKL is present".

.... Still I would prefer that to "PyCBC fails randomly", which will not be great for end-users to deal with!

**Comment by ahnitz** [comment]
@spxiwh While both libraries do export symbols of the same name, I am confused why that would be the problem as they are dynamically loaded. I don't think the namespace clash is actually an issue in that case. Certainly we couldn't link against both simultaneously, but we aren't doing that. 

I suspect some kind of process / thread manipulation on MKL's part that is confusing FFTW if it is run afterward. Maybe if FFTW is run first, the 'state' is already set, so MKL doesn't mess with it?

**Comment by ahnitz** [comment]
I believe this issues should be fixed by https://github.com/gwastro/pycbc/pull/4054

**Comment by ahnitz** [comment]
@spxiwh Please close if you think this is now addressed by the latest patch.
