### ISSUE TITLE
Update CVMFS envs to python3.9

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4100]
At the moment it's not easy to get the CVMFS builds to run on LVK machines. This is because the python 3.9 (and 3.6) libraries are available but not 3.8 (although one can find them via conda+igwn-py38 and adding to LD_LIBRARY_PATH).

I would propose updating these envs to python3.9 unless there are objections?

**Comment by GarethCabournDavies** [comment]
I think this is done - close?

**Comment by spxiwh** [comment]
```
(pycbc-v2.3.7) [ian.harry@ldas-osg 02:51 am hl]$ python --version
Python 3.9.18
```
