### ISSUE TITLE
get_td_waveform_modes argument

### ISSUE THREAD

**Issue by Cyberface** [gwastro/pycbc#4111]
I was just looking at `get_td_waveform_modes` and noticed that it seems to be requiring Fourier domain arguments i.e. `parameters.fd_required`. see: [waveform_modes.py#L322](https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform_modes.py#L322)

Is that a typo? Shouldn't it be `parameters.td_required`?

**Comment by ahnitz** [comment]
@cdcapano Poke

**Comment by cdcapano** [comment]
@Cyberface Yeah, you're right, that's a bug. Looks like get_fd_modes was copied and that wasn't adjusted.

**Comment by Cyberface** [comment]
sweet cheers!
