### ISSUE TITLE
PyCBC stat class shouldn't keep HDF files open

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4116]
The PyCBC stat class uses a lot of supplementary files for things like evaluating p(signal) and p(noise). These files are generally read once and then that data stored (good!). However, the HDF file objects are never closed and always attached to the class. It would be better to store the file *locations* and only open them when needed *and them close them immediately*. Without this the stat class cannot be pickled, which can be useful! It also decreases the risk of the weird HDF failures if one has forgotten to give the HDF_LOCKING env variable.

**Comment by titodalcanton** [comment]
I seem to remember that at some point the template bank file was also being kept open by PyCBC Live. Not sure if that is still true nowadays though.

**Comment by titodalcanton** [comment]
Yup, a quick check indicates that the bank, PTA files and even the SEOBNR ROM file are kept open all the time. They are all read-only at least, so the HDF_LOCKING issue should not be a problem I think.

**Comment by spxiwh** [comment]
For PyCBC Live this is not really a problem as it would either fail on start up, or be fine (and using read-only *should* also be safe). For the all-sky search, where many coinc jobs run it can be more of an issue.

**Comment by spxiwh** [comment]
... But in general, we should close files we are not using.

**Comment by titodalcanton** [comment]
Fixed by #4117.
