### ISSUE TITLE
key error in the  varying final frequency computation in `pycbc_aligned_stoch_bank`

### ISSUE THREAD

**Issue by khunsang** [gwastro/pycbc#4165]
Should the keys for masses in the [dictionary](https://github.com/gwastro/pycbc/blob/master/bin/bank/pycbc_aligned_stoch_bank#L235-L236) be `mass1` and `mass2`?    In [line 239 of pycbc_aligned_stoch_ban](https://github.com/gwastro/pycbc/blob/master/bin/bank/pycbc_aligned_stoch_bank#L239), the final frequency computations is giving key error.  I think, there, those computations are expecting [dictionary](https://github.com/gwastro/pycbc/blob/9118837c66cfac38bc23d6f53cedca571eac8a6a/pycbc/pnutils.py#L440) with keys `mass1, mass2, spin1z, spin2z `.

I was running bank generation with following command
`pycbc_aligned_stoch_bank -V --pn-order threePointFivePN \
    --f0 50 --f-low 20 --f-upper 1000\
    --bank-fupper-formula  SEOBNRv4Peak \ .......`

This gives me following error:

`2022-10-27 16:07:31,097 Initialize the PartitionedTmpltbank class
2022-10-27 16:08:16,014 Starting bank placement
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.3/bin/pycbc_aligned_stoch_bank", line 239, in <module>
    opts.bank_fupper_formula, mass_dict, fs)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.3/lib/python2.7/site-packages/pycbc/tmpltbank/coord_utils.py", line 752, in return_nearest_cutoff
    f_cutoff = cutoff_fns[name](mass_dict)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.3/lib/python2.7/site-packages/pycbc/pnutils.py", line 476, in <lambda>
    "SEOBNRv4Peak": lambda p: get_freq("fSEOBNRv4Peak", p["mass1"], p["mass2"],
KeyError: 'mass1'`

**Comment by spxiwh** [comment]
@khunsang Apologies I missed this one. Can you give the full bank generation command so I can check?

**Comment by khunsang** [comment]
HI @spxiwh ,  

No worries.  This full command is given below, 

`/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.16.6/bin/pycbc_aligned_stoch_bank -V --pn-order threePointFivePN \
    --f0 50 --f-low 20 --f-upper 1000\
    --bank-fupper-formula  SEOBNRv4Peak \
    --delta-f 0.01 \
    --min-match 0.97 \
    --min-mass1 0.5  --min-mass2 0.5 \
    --max-mass1 7.0 --max-mass2 3.0 --verbose \
    --max-total-mass 10.0 --min-total-mass 1.0 \
    --max-eta 0.25 --min-eta 0.083 \
    --ns-bh-boundary-mass 3 \
    --max-bh-spin-mag 0.99 --max-ns-spin 0.99 \
    --output-file o4_bank_Mtot_1_to_10_chi_0p99_GeoStoch.xml \
    --num-seeds 10000 \
    --num-failed-cutoff 1000000\
    --psd-file /home/khun.phukon/Work/UoB/fitting_factor/Bank/H1L1V1_o4_psd.txt \
    --random-seed 1915 \
    --f-low-column alpha6`

I got similar errors for `bank-fupper-formula=SchwarzISCO` and a few others.

**Comment by spxiwh** [comment]
@khunsang Okay, I notice that you are running from the old v1.16 release branch. We couldn't make changes to that branch, as it is now the frozen code we used for the O3 analyses, but I do want to make sure this runs on modern releases. SO:

```
/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_8/virtualenv/pycbc-v2.0.5/bin/pycbc_aligned_stoch_bank --verbose --pn-order threePointFivePN --f0 50 --f-low 20 --f-upper 1000 --bank-fupper-formula SEOBNRv4Peak --delta-f 0.01 --min-match 0.97 --min-mass1 0.5 --min-mass2 0.5 --max-mass1 7.0 --max-mass2 3.0 --verbose --max-total-mass 10.0 --min-total-mass 1.0 --max-eta 0.25 --min-eta 0.083 --ns-bh-boundary-mass 3 --max-bh-spin-mag 0.99 --max-ns-spin 0.99 --output-file o4_bank_Mtot_1_to_10_chi_0p99_GeoStoch.xml --num-seeds 10000 --num-failed-cutoff 1000000 --psd-model aLIGOZeroDetHighPower --random-seed 1915 --f-low-column alpha6
```

Seems to work fine. Note that if there is no python3.8 library available I need to do:

```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38/lib
```

To get the necessary python3.8 libraries. I think I resolved this for the next release by moving to python3.9.

**Comment by khunsang** [comment]
Thanks a lot Ian.
