### ISSUE TITLE
Store candidate-related files into an independent directory

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4197]
Here is something I wanted to do for years but never got to, and maybe others have better ideas. I think it is important we do this before O4 starts.

Upon generating a candidate event, PyCBC Live stores multiple files related to it under its base output directory (given by `--output-path`). When operating for many months, potentially years, this fills the directory with thousands and thousands of files.

I propose instead that files for a candidate end up in `base/YYYY_MM_DD/candidate_{merger_time:.3f}_{random}/` where `base` is the base directory, `merger_time` is what the files are currently named with, `YYYY_MM_DD` is the UTC date of that merger time, and `random` is a random string used to disambiguate candidates with the same merger time to ms precision (already used currently).

Do people see clear drawbacks with this approach?

**Comment by tdent** [comment]
Closed by #4206
