### ISSUE TITLE
Do not hardcode mass-gap definition in PyCBC Live

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4300]
The definition of the "mass gap" in PyCBC Live is currently hardcoded in the io/live module, specifically here: https://github.com/gwastro/pycbc/blob/master/pycbc/io/live.py#L271-L273. This is a scientific parameter that should ideally not be defined in that module, and it would be nice to have it controllable by the user in a clear way. Design a clearer way to organize the source classification parameters, e.g. similarly to what is done for P(astro).

**Comment by tdent** [comment]
(Noting that this is only done for an extra 'EmBright' calculation beyond the mass-based classification.)

**Comment by titodalcanton** [comment]
Fixed by #4306.
