### ISSUE TITLE
Invalid attribute name for condor submission

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4348]
I get an error that `+DAGNodeRetry` is an invalid attribute name when trying to run an offline workflow.

```
05/02/23 06:35:45 submitting: /usr/bin/condor_submit -a dag_node_name=create_dir_o3_singles.dax_0_local -a My.DAGManJobId=314004145 -a DAGManJobId=314004145 -batch-name o3_singles.dax-0.dag+314004145 -batch-id 314004145.0 -a submit_event_notes' '=' 'DAG' 'Node:' 'create_dir_o3_singles.dax_0_local -a dagman_log=/home/gareth.cabourndavies/test_codes/pycbc/offline_singles/output_update_2/pycbc-tmp_m93wrfs2/work/./o3_singles.dax-0.dag.nodes.log -a My.DAGManNodesMask="0,1,2,4,5,7,9,10,11,12,13,16,17,24,27,35,36" priority=800 JOB=create_dir_o3_singles.dax_0_local +DAGNodeRetry=0 DAG_STATUS=0 FAILED_COUNT=0 My.KeepClaimIdle=20 -a notification=never My.DAGParentNodeNames="" ./create_dir_o3_singles.dax_0_local.sub
05/02/23 06:35:45 From submit: condor_submit: invalid attribute name '+DAGNodeRetry' for attrib=value assigment
05/02/23 06:35:45 failed while reading from pipe.
05/02/23 06:35:45 Read so far: condor_submit: invalid attribute name '+DAGNodeRetry' for attrib=value assigment
05/02/23 06:35:45 ERROR: submit attempt failed
```

**Comment by GarethCabournDavies** [comment]
Note this may not be pycbc, but rather a pegasus/condor interaction thing

**Comment by spxiwh** [comment]
I've been included on a thread with pegasus + Condor regarding this. If I'm understanding correctly, this may be a bug in [a recent] condor build. As this is in *all* our submit files, it's going to be painful until it can be resolved.

**Comment by spxiwh** [comment]
@ahnitz Fixes are coming (to both condor and pegasus, either of which fixes this).

However, there is a simple temporary workaround, which would avoid needing to revert condor (which would be bad as we also need features in the latest condor release for running over OSG).

In short just set:
```
export _CONDOR_DAGMAN_DEFAULT_APPEND_VARS=True
```
and this goes away!

**Comment by GarethCabournDavies** [comment]
Is this fix in @spxiwh?

**Comment by spxiwh** [comment]
I think the fix is in ... And LDG clusters are now setting this as default condor config anyway. It doesn't harm to keep this line in any run scripts though.

**Comment by GarethCabournDavies** [comment]
Okay, I think the issue can be closed now then
