### ISSUE TITLE
attempting to make local_site_scratch directory when not using local site

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4349]
The offline workflow I am running is trying to run the `create_dir_o3_singles.dax_0_local` job, this makes no sense, as I am not using the local site for submitting the workflow. This then fails, as the `local_site_scratch` directory above this has not been made

**Comment by spxiwh** [comment]
Can you provide more details for how to reproduce this?

**Comment by spxiwh** [comment]
@GarethCabournDavies I tried to reproduce this. My `executables.ini` reads:

```
[pegasus_profile]
condor|request_memory = 1000
condor|request_disk = 1000
condor|accounting_group = ligo.dev.o4.cbc.bbh.pycbcoffline
pycbc|primary_site = condorpool_symlink

[pegasus_profile-results_page]
pycbc|site = condorpool_shared
```

The workflow is currently working through jobs ... I was expecting an immediate failure. This is the PyCBC example search workflow, where I just removed about 15 lines to reduce executables.ini to this content (after the list of exes). Is there anything else I might need to do here??

**Comment by spxiwh** [comment]
@GarethCabournDavies Any idea about this one? The directory itself `/home/gareth.cabourndavies/.../output/local-site-scratch/work` doesn't make sense, as this should be under some local directory unless overwritten (the example workflow does set the option to put the local-site-scratch somewhere else, and that option may have ended up in places it shouldn't be).

**Comment by GarethCabournDavies** [comment]
I'm not sure - this could have been a transient issue, as I havent hit it the last couple of times I've submitted workflows

**Comment by spxiwh** [comment]
Closing for now then.
