### ISSUE TITLE
Add GitPython into CVMFS venv builds

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4352]
When trying to use the CVMFS venv I see:

```
Pegasus requires the Python3 GitPython module to be installed
Please install it via your OS package manager, via pip, or activate a venv which includes the module.
```

I guess we need to add this as a dependency if pegasus isn't pulling it automatically.

**Comment by GarethCabournDavies** [comment]
would it be preferable to report this back to pegasus? They [mention](https://pegasus.isi.edu/documentation/user-guide/installation.html#pegasus-from-tarballs) manually installing gitpython and pyyaml if building from source, but not from pip

**Comment by spxiwh** [comment]
I think this is actually fixed by the tactic of setting `PEGASUS_PYTHON`. But I do have a list of questions to pass on to pegasus in the next few weeks.

**Comment by spxiwh** [comment]
Nevertheless, the latest CVMFS build includes this, so as written the issue is resolved.
