### ISSUE TITLE
Syntax error in activate-binutils_linux-64.sh in GitHub CI

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4355]
Recently, I've seen quite a few CI builds fail with:

```
.tox create: /home/runner/work/pycbc/pycbc/.tox/.tox
.tox installdeps: tox-conda, tox >= 3.28.0
GLOB sdist-make: /home/runner/work/pycbc/pycbc/setup.py
py-docs create: /home/runner/work/pycbc/pycbc/.tox/py-docs
py-docs installcondadeps: mysqlclient, gcc_linux-64, gxx_linux-64, gsl, lapack==3.6.1
py-docs installdeps: :preinstall:-rrequirements.txt, -rcompanion.txt, mkl;'arm' not in platform_machine, git+https://github.com/mikekatz04/BBHx.git; sys_platform == 'linux', git+https://github.com/ConWea/BBHX-waveform-model.git; sys_platform == 'linux'
ERROR: invocation failed (exit code 2), logfile: /home/runner/work/pycbc/pycbc/.tox/py-docs/log/py-docs-2.log
================================== log start ===================================
/tmp/tmp6bla0lcg: 5: /home/runner/work/pycbc/pycbc/.tox/py-docs/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
```

(For e.g. https://github.com/gwastro/pycbc/actions/runs/4873364584/jobs/8800157383)

This is odd, because this seems to be this issue:

https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/60

which was fixed some time ago! This also isn't reproducible. Sometimes it happens, sometimes not, and I don't know why. I might try pinning https://anaconda.org/conda-forge/binutils_linux-64 to the latest version (as of today) or above, in addition to specifying versions on gcc_linux-64 and gxx_linux-64 in the "conda_deps" in tox.ini .... Unless anyone has any better ideas??

**Comment by titodalcanton** [comment]
I confirm have seen this issue, but I always assumed it was some temporary failure somewhere on the planet.

**Comment by spxiwh** [comment]
I wrote it off like that the first time as well, but it's now happened too many times.
