### ISSUE TITLE
spa_tmplt understands f upper but not f final

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#4366]
See https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/spa_tmplt.py#L217 vs. eg https://github.com/gwastro/pycbc/blob/master/pycbc/waveform/waveform.py#L633 

While the waveform code will work if someone calling it knows to use f_upper when using spa_tmplt and f_final when using any lalsimulation waveform, and puts in the appropriate (and probably messy) switches, it will not work properly otherwise.

**Comment by titodalcanton** [comment]
As far as I can tell, spa_tmplt is the only place where `f_upper` is used. PyCBC Live's bank uses a `f_final` dataset, which is consistent with what the PreTaylorF2 approximant understands.

I guess this could be "fixed" by adding support for `f_final` in spa_tmplt, keeping the support for `f_upper`, but printing a warning when that is used.
