### ISSUE TITLE
PyCBC Live can *still* create invalid SNR timeseries in the LIGOLW files

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4370]
Spotted by Cody on the MDC analysis:

> I see a ValueError with the message "BAYESTAR expects the SNR time series to be centered on the single-detector trigger times, but V1 was off by 0.0551757825 s"

This is event G1060099, from the SNR optimizer. At the sample rate we are using for the analysis, the time offset almost exactly corresponds to an offset of 113 samples. I suspect it may be an edge case related to data availability, but to be verified.

**Comment by tdent** [comment]
Checking if this is still open

**Comment by titodalcanton** [comment]
We have discovered several similar cases recently, and we think this is now fixed by #4655. Will close when the fix is confirmed on the O3 replay MDC.

**Comment by titodalcanton** [comment]
@maxtrevor are we happy that this bug has been fixed?

**Comment by maxtrevor** [comment]
Happy to say that this error has not been seen on the MDC in weeks, closing
