### ISSUE TITLE
Bug in LISA example?

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [gwastro/pycbc#4372]
Hi,

I'm trying to run the [LISA example from the pycbc docs](https://pycbc.org/pycbc/latest/html/inference/examples/lisa_smbhb_inj_pe.html).

To do so, I've installed `pycbc`, [`BBHx`](https://github.com/mikekatz04/BBHx), and [`BBHX-waveform-model`](https://github.com/ConWea/BBHX-waveform-model) in a conda environment.

After that, I ran `injection_smbhb.sh` (same name as in the docs) with the same `.ini` file as in the docs, which produces the expected hdf5 file.

Upon running `lisa_smbhb_relbin.sh`, however, I get the following exception:
```
Traceback (most recent call last):
  File "<conda-env-path>/bin/pycbc_inference", line 129, in <module>
    model = models.read_from_config(cp)
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inference/models/__init__.py", line 185, in read_from_config
    return get_model(name).from_config(cp, **kwargs)
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inference/models/gaussian_noise.py", line 582, in from_config
    strain_dict, psd_strain_dict = data_from_cli(opts, **data_args)
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inference/models/data_utils.py", line 424, in data_from_cli
    strain_dict = strain_from_cli_multi_ifos(opts, instruments,
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inference/models/data_utils.py", line 50, in strain_from_cli_multi_ifos
    return strain.from_cli_multi_ifos(*args, **kwargs)
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/strain/strain.py", line 442, in from_cli_multi_ifos
    strain[ifo] = from_cli_single_ifo(opt, ifo,
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/strain/strain.py", line 431, in from_cli_single_ifo
    return from_cli(single_det_opt,
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/strain/strain.py", line 312, in from_cli
    injector.apply(strain, opt.channel_name.split(':')[0],
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inject/inject.py", line 570, in apply
    signal = self.make_strain_from_inj_object(inj, delta_t,
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/inject/inject.py", line 631, in make_strain_from_inj_object
    strain = get_td_det_waveform_from_fd_det(
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/waveform/waveform.py", line 875, in get_td_det_waveform_from_fd_det
    return _base_get_td_waveform_from_fd(template, rwrap, **params)
  File "<conda-env-path>/lib/python3.9/site-packages/pycbc/waveform/waveform.py", line 769, in _base_get_td_waveform_from_fd
    _filter_time_lengths[nparams['approximant']](
  File "<conda-env-path>/lib/python3.9/site-packages/BBHX_PhenomD.py", line 35, in imr_duration
    nparams = {'mass1':params['mass1'], 'mass2':params['mass2'],
KeyError: 'mass1'
```

Is there anything I'm missing? Did anything change in these packages with respect to the time where this example was put together?

Thank you very much in advance,

**Comment by ahnitz** [comment]
@Rodrigo-Tenorio We'll try to help sort this out. @WuShichao can possibly also help, but some additional information to help reproduce this problem would be useful.

 Can you tell us what version of PyCBC you installed? If possible, can you install the latest version from master.

To give context, these examples are run on every PR so we never break them (that's the idea anyway, could be a corner case). The docs pages show output using the most recent PR and isn't actually a static page. 

I also just verified myself that I can run the example.  The error you are seeing, seems to me like as if the injection didn't have a 'mass1' parameter. Did you modify the injection file?  

I assume you made the "lisa_smbhb_relbin.sh" yourself. I only ask because our file is named somewhat differently, so want to check we are running the same thing. If you clone the pycbc repo, you can find the scripts in the examples/inference/lisa_smbhb_inj folder. If you go there and reproduce exactly what I just tried, do you get the same error? 

```
bash injection_smbhb.sh
bash run.sh
```

**Comment by Rodrigo-Tenorio** [comment]
Hi @ahnitz , thank you for the fast response.

Here are the versions of the relevant packages:
```
bbhx                          1.0.5
PyCBC                         2.2.0
pycbc-bbhx-plugin             0.0.dev0
```

The `lisa_smbhb_relbinsh.sh` looks like `examples/inference/lisa_smbhb_inj/run.sh` except for the last `--verbose` option (which I just added).

> I also just verified myself that I can run the example. The error you are seeing, seems to me like as if the injection didn't have a 'mass1' parameter. Did you modify the injection file?

No, both files are copy & pasted as they are from the documentation.

> If possible, can you install the latest version from master.

It looks like installing `pycbc` from master rather than from the latest release (2.2.0) solved this problem (i.e. I was able to reproduce the plot).

Any opinion on whether I should be working on the edge of pycbc or just wait for the next release and stay there?

Thank you very much for your help.

**Comment by ahnitz** [comment]
@Rodrigo-Tenorio The LISA work is definitely on the cutting (bleeding?) edge, so if you want to work with that (or perhaps contribute / provide input on) it would be helpful to work from master. You are also welcome in our slack workspace.

I see you have ligo.org address. If you join with that, you don't need any permission to join. 

gw-astro.slack.com

If you want to use a different email as your account, we can send an invite.

**Comment by Rodrigo-Tenorio** [comment]
Great, thank you very much @ahnitz, I will take note of this.

I just joined the slack space, thanks for the link.

The problem was solved, so I'll close the link.

**Comment by WuShichao** [comment]
@Rodrigo-Tenorio @ahnitz Just see this closed issue. Good to know it's already been solved :)
