### ISSUE TITLE
MKL doesn't work with an array longer than 2^24 points

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#4395]
If one tries to run the LISA inference example using an MKL backend the code fails with `Intel MKL DFTI ERROR: Invalid configuration parameters`. I believe this is the same error as https://github.com/IntelPython/mkl_fft/issues/57, and seemed to be caused there by array sizes > 2^24. (Indeed the LISA example first successfully does an FFT of length 12614400 before failing at length 19457280). 

LIGO arrays are generally not as long as this, but it will be common to have lengths like this in LISA, so avoiding MKL in that context might be needed (especially if we move to MKL as default FFT backend).

**Comment by ahnitz** [comment]
To add to this, it does work if you keep to powers of 2, but after 2**24, it seems that any other length returns this error.

**Comment by ahnitz** [comment]
Shot in the dark, but in case someone on the community forums has a suggestion, I made a post here https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Intel-MKL-DFTI-ERROR-Invalid-configuration-parameters-for-1d-FFT/m-p/1496284#M34669

**Comment by GarethCabournDavies** [comment]
Can this be closed as fixed by #4583?

**Comment by spxiwh** [comment]
Yes
