### ISSUE TITLE
Fine tuning iDQ flag plots

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#4484]

**Comment by tdent** [comment]
Comment from Tito: 'are those rates per bin, or per template?'

Comments from Tom: 
```
What is plotted is labeled 'relative rates', I can guess what that means, but with my 'does it help review' hat on I would make the label more explicit.

Ie when Alan sees that, he's going to say 'relative to what, though?'

Also the y axis is necessarily starting at relative rate 1?, what happens when the 'relative rate' is less than 1?
```

**Comment by tdent** [comment]
Further comments .. 
- If the 'relative trigger rate' measurement logically comes before the 'DQ Log Likelihood' which I assume is a contribution to the ranking stat, the trigger rate axis should be on the left and the logL axis on the right.  I.e. the change to the stat results _from_ the difference in trigger rates (I think). 
- From your explanations about the 'when using a flag' comment, it seems like this code should only be used to plot DQ files which have exactly two DQ values, ie off/on.  Would it be clearer and more foolproof to put in an assertion that the length of the DQ value dataset/array is exactly 2?  (Otherwise it will still make a plot for the timeseries case, but it will be hard to interpret the plot properly ..)

**Comment by maxtrevor** [comment]
> Comment from Tito: 'are those rates per bin, or per template?'
> 
> Comments from Tom:
> 
> * What is plotted is labeled 'relative rates', I can guess what that means, but with my 'does it help review' hat on I would make the label more explicit.  Ie when Alan sees that he's going to say 'relative to what, though?'  So I could suggest e.g. '(Rate during DQ flag)/(mean rate)'
> * Also is the y axis necessarily starting at relative rate 1? - ie what happens when the 'relative rate' is less than 1?

Indeed the trigger rate is relative to the mean trigger rate so te suggested label makes sense.
If the true relative rate is less than 1, the relative rate in the file produced by pycbc_rerank_dq will be 1. This was done to avoid upranking triggers, which I was told to avoid at the PyCBC f2f in Portsmouth last year. This plot script reads the file produced by pycbc_rerank_dq, so it will necessarily always be 1 or greater.

**Comment by maxtrevor** [comment]
> Further comments ..
> 
> * If the 'relative trigger rate' measurement logically comes before the 'DQ Log Likelihood' which I assume is a contribution to the ranking stat, the trigger rate axis should be on the left and the logL axis on the right.  I.e. the change to the stat results _from_ the difference in trigger rates (I think).
> * From your explanations about the 'when using a flag' comment, it seems like this code should only be used to plot DQ files which have exactly two DQ values, ie off/on.  Would it be clearer and more foolproof to put in an assertion that the length of the DQ value dataset/array is exactly 2?  (Otherwise it will still make a plot for the timeseries case, but the legend text will be wrong and it will be hard to interpret the values shown ..)

I think these suggestions both make sense. The logL axis is the quantity used in the ranking stat, calculated by taking the natural log of the relative trigger rate.

**Comment by tdent** [comment]
Closing as addressed by the PR.
