### ISSUE TITLE
Add ability to choose the order of injections in followup

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4498]
The injection minifollowup order choice is currently in a try/except without warnings:

https://github.com/gwastro/pycbc/blob/e8477cb855dd6c17576eca1e643c4c0b991bcb18/bin/minifollowups/pycbc_injection_minifollowup#L109

This means that we cannot tell which method was used, and we do not have ability to tell the minifollowup to use a different order

**Comment by tdent** [comment]
Addressed by #4602
