### ISSUE TITLE
Should the Live single trigger fitting be so slow?

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4501]
While testing #4486, I found myself waiting hours for various test runs of `pycbc_live_single_trigger_fits` to finish. Having always assumed that it was limited by I/O on a slow filesystem, I moved the input triggers to a directory in `/local`, and was surprised to find that it did not matter much, so I investigated a bit more.

The slowness does not seem to actually depend much on the filesystem: it takes about the same time to run `pycbc_live_single_trigger_fits` from a set of files in `/local` and from the same set of files in `/dev/shm` and in my home directory. In both cases I observed that the process occupies ~100% CPU time while reading the triggers, and by using the "I/O" tab of `htop`, I observed that the data read rate is only a few Mb/s (it seems to be higher at the beginning and quickly taper down to ~1.5 Mb/s). So I no longer believe that the limiting factor is technically I/O, though the slow part is definitely reading the triggers.

Here is one of the profiling graphs I made (details [here](https://ldas-jobs.ligo.caltech.edu/~tito.canton/pycbc/live/single_fits_are_slow/), sorry non-LVK members), this is reading from `/dev/shm`:

![image](https://github.com/gwastro/pycbc/assets/11317236/956ea3db-33d3-41e3-a8cb-74074d0e3ea3)

I am a bit rusty in interpreting these graphs, but I think this means about 64% of the time is spent in some Numpy function called by `concatenate()`. I suppose that is good in some sense, but maybe if we were using a different way to store (or just read) the triggers, we could be much faster?

**Comment by titodalcanton** [comment]
The `hdf:164` in one of the green boxes in my profile plot above refers to the `pycbc/io/hdf` module, specifically the `__add__` method of the DictArray class. So a ton of time is spent slowly inflating a DictArray by relatively tiny increments. Maybe if we could preallocate a much larger DictArray beforehand, and reduce the number of calls to `concatenate()`, things could be significantly faster?

**Comment by titodalcanton** [comment]
…of course, this is only annoying if you forget the `--trigger-cuts new_snr:6.75:lower` option :picard:

**Comment by GarethCabournDavies** [comment]
Should we close this, or are we happy that (if using the efficiency options) the efficiency is good?

**Comment by titodalcanton** [comment]
I am convinced that the code is still being inefficient in how it reads the triggers, but in a way that is probably not problematic in normal use cases, so we can probably close this.
