### ISSUE TITLE
SNR opt differential evolution init and verbosity

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#4555]
The init arrays should be actual parameter values (randomized within bounds), not 0-1 random variables.  The bad consequence of feeding in 0-1 variables is that for almost all events the chirp mass is stuck to the lower bound (due to the scipy init function's clipping) for the entire minimization, i.e. the output is forced to use a bad chirp mass value.  (Also the number of independent eta and chi_1,2 points is greatly reduced, but this is less critical.) 

@PRAVEEN-mnl and I found this by printing out the parameter values and SNR at every call to the network SNR function, and I think there should also be a 'debug' level of verbosity to do this (for every choice of optimizer) as the SNR optimizer as a whole seems quite liable to breakage.

**Comment by GarethCabournDavies** [comment]
Is this solved by the merged MR?

**Comment by tdent** [comment]
Looks like it.
