### ISSUE TITLE
pycbc_process_sngls looks to have been abandoned - should we get rid of it?

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4589]
This hasnt been touched beyond find/replace-style PRs for a few years, is this still used / useful?

**Comment by titodalcanton** [comment]
Looks like the original authors were @tdent and @spxiwh, but it also looks like I contributed a few years ago. I *think* this is what I used to get the PyCBC single triggers for [arXiv:2210.15633](https://arxiv.org/abs/2210.15633), but I cannot confirm at the moment. This might still be useful, but it would be worth explanining better in the docstring what it is useful for.

**Comment by titodalcanton** [comment]
Actually I can confirm that `pycbc_process_sngls` is what I used for [arXiv:2210.15633](https://arxiv.org/abs/2210.15633), details in `~/o3/pycbc_offline_runs/hlv/c01/clustered_single_triggers` at CIT.

I would not remove it.

**Comment by GarethCabournDavies** [comment]
Thanks for confirmation
