### ISSUE TITLE
Vetoes

### ISSUE THREAD

**Issue by pannarale** [gwastro/pycbc#4702]
- [ ] In `def load_triggers(input_file, vetoes):` (pycbc/pycbc/results/pygrb_postprocessing_utils.py) the vetoes need to be implemented.  There should be old (xml) code in PR #3972.  A rough scheme is
```
# =============================================================================
 # Veto trigger
 # =============================================================================
 def veto_trig(trigs, trial_dict):
    """Remove trigs that are not in trial dict"""
     mask = []
     for time in trigs['network/end_time_gc']:
        mask.append(any([time in trial for trial in trial_dict]))
     return {key: trigs[key][mask] for key in trigs.keys()}
```
but we are using hdf and not dictionaries so the last line needs updating.

- [ ] `pycbc_multi_inspiral` contains
```
[...]
from pycbc.vetoes import sgchisq
[...]
sgchisq.SingleDetSGChisq.insert_option_group(parser)
[...]
```
which does not do anything productive [we would need to call `sg_chisq = sgchisq.SingleDetSGChisq.from_cli(opt, bank, opt.chisq_bins)` and output `sg_chisq.values(...)].  Having said that, PyGRB uses banks with long templates (NSBH, BNS): we should simply remove this veto for short transients (BBHs with mass above $60 M_\odot$), but if one day anyone uses PyGRB with high-mass BBHs, then it would turn out to be a shortcoming.

- [ ] The vetoed injections category is ambiguous in `pycbc_pygrb_page_tables`. It used to contain vetoed injections by looking for cases with reweighted SNR = 0, but now the cut by reweighted SNR threshold happens here (and similarly in other post-processing scripts) and not in `pycbc_multi_inspiral`. At the same time, vetoes are not in yet, so we are simply counting injections cut away by the reweighted SNR threshold.

**Comment by MarcoCusinato** [comment]
A bit more refined, and working, version of the function at the first point can be found [here](https://github.com/MarcoCusinato/pycbc/blob/vetoes/pycbc/results/pygrb_postprocessing_utils.py#L333)

**Comment by pannarale** [comment]
https://github.com/gwastro/pycbc/pull/4929 has started the work to incorporate ditcher vetoes in PyGRB analyses.

**Comment by pannarale** [comment]
This saga ends with PR https://github.com/gwastro/pycbc/pull/4979: data quality veto handling is in PyGRB to the best of our knowledge.  We will keep the `SingleDetSGChisq` veto in to avoid having users need to insert it back in if they want to run with high-mass BBHs in their template banks.
