### ISSUE TITLE
Backport #4699 for 2.1.x release series

### ISSUE THREAD

**Issue by duncanmmacleod** [gwastro/pycbc#4708]
It would be great to backport #4699 (fixes #4698) to the 2.1.x release series, if possible.

**Comment by psteinb** [comment]
Porting back this fix would be super lovely!

**Comment by maxtrevor** [comment]
I just saw this issue for the first time despite apparently being assigned months ago.
I don't think any action is needed for this. We are currently planning to make a new release branch based on master for the next pycbc live update, which should include https://github.com/gwastro/pycbc/pull/4699 automatically.

**Comment by spxiwh** [comment]
I don't understand why it is important/necessary to include this in the 2.1.x release branch. That branch is used for a LVK analysis, whose environment is controlled by us. It should not be being used by anything else (v2.4.2 is the latest release as of writing this, and includes this, and the broad PyCBC package will support numpy 2 ASAP).

**Comment by titodalcanton** [comment]
I agree with @maxtrevor and @spxiwh. Closing.
