### ISSUE TITLE
Duplicated GW150914 checker code

### ISSUE THREAD

**Issue by GarethCabournDavies** [gwastro/pycbc#4793]
https://github.com/gwastro/pycbc/blob/v2.4.0/examples/inspiral/check_GW150914_detection.py and https://github.com/gwastro/pycbc/blob/v2.4.0/tools/einsteinathome/check_GW150914_detection.py are identical except for some minor comments at the top

Can (one of) these be removed?

**Comment by spxiwh** [comment]
Probably the second one can now be removed.
