### ISSUE TITLE
Absence of foreground triggers causing error in statmap jobs

### ISSUE THREAD

**Issue by Prasia-Pankunni** [gwastro/pycbc#4907]
While doing MDC search, for some chunks, I am getting the error:
```
File "/home/prasia.p/o4_pycbcv2.3.7/bin/pycbc_coinc_statmap", line 325, in <module>
    ifar_foreground = ifar_exc
NameError: name 'ifar_exc' is not defined
```
This is in the directory `/home/prasia.p/automation_test/MDC/MS220425h/chunk15` and in the osg2 node. 
The executable is `submitdir/work/O4a-main.dax_O4a-main/statmap/statmap_ID16_ID0000461.sh`. 

It seems like there are no enough clustered foreground triggers. However, as @spxiwh confirms, this code is supposed to work in this case. Could you please suggest what could be done for such cases ? This happens or a few number of chunks.

**Comment by spxiwh** [comment]
@GarethCabournDavies Can you take a look at this? `coinc_statmap` definitely seems to have a failure mode if no foreground triggers are present, which is not desired.

**Comment by GarethCabournDavies** [comment]
Okay, I see whats gone wrong - I'll add a patch, which can go onto both master and v23 branch

**Comment by GarethCabournDavies** [comment]
Tested patch works with coinc_statmap - I will need to test on later codes though

**Comment by GarethCabournDavies** [comment]
@Prasia-Pankunni could you check whether the patch in #4908 allows the full workflow to run, or does it hit a snag downstream?

**Comment by Prasia-Pankunni** [comment]
> @Prasia-Pankunni could you check whether the patch in #4908 allows the full workflow to run, or does it hit a snag downstream?

Yes, I can check..

**Comment by GarethCabournDavies** [comment]
The `page_snrchi` error is unusual - so there are no un-vetoed triggers at all in the single-detector file? If so, I'm not sure that this is a use-case we really want to support.
I think you could also try reducing `--min-snr` to 5?

For `plot_singles_vs_params`, this works on main branch, but not on the v23_release_branch which you are working on. I would again suggest to reduce `--min-z` on your config to 5, as that should fix the problem in your case on the v23 release branch.

**Comment by GarethCabournDavies** [comment]
I'm happy that the error is gone now though, so merging #4908 will close this issue
