### ISSUE TITLE
Bug in pycbc.detector.get_available_detectors()

### ISSUE THREAD

**Issue by divyajyoti09** [gwastro/pycbc#4927]
The output of `get_available_detectors()` is simply a repeated list of `get_available_lal_detectors()` without the full names. A simple test code demonstrates this:

```
import numpy as np
from pycbc.detector import get_available_detectors, get_available_lal_detectors

print(len(get_available_detectors(), get_available_lal_detectors()))

flag = True
for key in get_available_detectors():
    if key not in np.array(get_available_lal_detectors())[:,0]:
        print(key)
        flag = False
if flag:
    print("No unique keys in get_available_detectors()")
```
Output:
```
40 20
No unique keys in get_available_detectors()
```

**Comment by ahnitz** [comment]
@divyajyoti09 What is the bug here? This all appears correct to me. There will only be additional detectors in the full list if you have another source of detectors. This would happen you use a detector configuration file for example. 

See e.g an example here https://github.com/ahnitz/ce_location/blob/master/detectors.ini.

**Comment by divyajyoti09** [comment]
Ah, I understand. Although I still think that `get_available_detectors()` should not be repeating the list of LAL detectors twice. 

Also, is there a reason the full name of the detectors is not displayed in this function?

**Comment by ahnitz** [comment]
@divyajyoti09 Ah, got it, repetition in the list is a bug, yet. As to your second point, a lot of detectors have no concept of a 'full name' only a detector prefix code which is what you use in practice for functionality.

**Comment by ahnitz** [comment]
@divyajyoti09 Can you submit a PR to address the repetition?

**Comment by divyajyoti09** [comment]
@ahnitz Created a pull request here: https://github.com/gwastro/pycbc/pull/4928
