### ISSUE TITLE
OverflowError in  pycbc_multi_inspiral script because of numpy 2.x

### ISSUE THREAD

**Issue by Thomas-JACQUOT** [gwastro/pycbc#4956]
I was running some tests by following this [repository](https://git.ligo.org/publications/o4/Burst/o4a-grb/-/wikis/PyGRB-Analysis:PyGRB-instructions) and most part of my jobs failed and gave me this error : 

```python
Traceback (most recent call last):
  File "/home/thomas.jacquot/.conda/envs/pygrb-cal-test/bin/pycbc_multi_inspiral", line 688, in <module>
    idx_dict = {
               ^
  File "/home/thomas.jacquot/.conda/envs/pygrb-cal-test/bin/pycbc_multi_inspiral", line 693, in <dictcomp>
    idx[ifo]
OverflowError: Python integer -19 out of bounds for uint32

2024-11-25 04:40:48,921:ERROR:pegasus-analyzer(1515): Workflow Failed  wf_uuid: 3222eaeb-e919-40c2-8cea-7957c0a09af6 submit dir: /local/thomas.jacquot/pycbc-tmp_js4yehym/work
2024-11-25 04:40:48,921:ERROR:pegasus-analyzer(2147): One or more workflows failed
``` 
I've found out thanks to test that this error is coming from my numpy version (2.1.3) as the following code is showing it : 

```python

In [1]: import numpy as np

In [2]: np.uint32(-19)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[2], line 1
----> 1 np.uint32(-19)

OverflowError: Python integer -19 out of bounds for uint32
In [3]: exit()
(envtest) jacquot@ll-jacquot:~$ conda list numpy
# packages in environment at /home/jacquot/miniconda3/envs/envtest:
#
# Name                    Version                   Build  Channel
numpy                     2.1.3           py311h08b1b3b_0  
numpy-base                2.1.3           py311hf175353_0 
``` 

And by changing the version of numpy the problem does not exist anymore : 

```python

In [1]: import numpy as np

In [2]: np.uint32(-19)
<ipython-input-2-5d2cc34e6e70>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -19 to uint32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.uint32(-19)
Out[2]: 4294967277

In [3]: exit()
(envtest) jacquot@ll-jacquot:~$ conda list numpy
# packages in environment at /home/jacquot/miniconda3/envs/envtest:
#
# Name                    Version                   Build  Channel
numpy                     1.24.3          py311h08b1b3b_1  
numpy-base                1.24.3          py311hf175353_1  

``` 

So I think something can be improve in `pycbc_multi_inspiral` to avoid this error for the future ?

**Comment by spxiwh** [comment]
@Thomas-JACQUOT I don't this is a numpy version issue. Doing `numpy.uint32(-19)` is a bug (if one *really* wants the wraparound, it can be done with % MAX_UINT_32, but I'm pretty sure that 4294967277 is not intended here).

**Comment by titodalcanton** [comment]
I think the problem is here: https://github.com/gwastro/pycbc/blob/master/bin/pycbc_multi_inspiral#L694-L696.
We are doing
```python
idx[ifo] - time_delay_idx[slide][position_index][ifo] < len(snr_dict[ifo])
```
when in reality we should do
```python
idx[ifo] < time_delay_idx[slide][position_index][ifo] + len(snr_dict[ifo])
```

**Comment by titodalcanton** [comment]
Ok, here is some fun stuff after further discussion with @Thomas-JACQUOT.

Consider this test code:
```python
import numpy as np

print(f'Numpy version is {np.__version__}')

x = np.ones(1, dtype=np.uint32)
y = 19
z = x + y

print(f'z = {z} of type {z.dtype}')
```
Let's run it with two versions of Numpy:
```
Numpy version is 2.1.2
z = [20] of type uint32
```
and
```
Numpy version is 1.24.3
z = [20] of type uint32
```
Both versions preserve the dtype and lead to an arithmetically correct result. Now let's change `y = -19`:
```
Numpy version is 2.1.2
Traceback (most recent call last):
  File "/home/tito/test_uint.py", line 7, in <module>
    z = x + y
        ~~^~~
OverflowError: Python integer -19 out of bounds for uint32
```
and
```
Numpy version is 1.24.3
z = [-18] of type int64
```
The old version promotes the output type to a signed integer and leads to the arithmentically correct result, while the new one raises the same error as initially seen. Now let's also change `z = x - y` (the test would now be equivalent to what `pycbc_multi_inspiral` does):
```
Numpy version is 1.24.3
z = [20] of type int64
```
and
```
Numpy version is 2.1.2
Traceback (most recent call last):
  File "/home/tito/test_uint.py", line 7, in <module>
    z = x - y
        ~~^~~
OverflowError: Python integer -19 out of bounds for uint32
```
Same result as before. Finally, what happens with `y = 19` and `z = x - y`?
```
Numpy version is 2.1.2
z = [4294967278] of type uint32
```
and
```
Numpy version is 1.24.3
z = [4294967278] of type uint32
```
Again, no type promotion and expected result (not arithmetically of course, but as expected for a modular type).

So it seems Numpy > 2 just prohibits adding or subtracting negative integers from uint32 arrays, regardless of whether the result would be arithmetically correct, and it does not seem to do any kind of type promotion. I guess this is just how Numpy 2's [type promotion](https://numpy.org/doc/stable/reference/arrays.promotion.html) works, so we should probably make the code more robust to this, i.e. not rely on type promotions (even when they seem very reasonable).

Sometimes I do miss strongly typed languages.

**Comment by Thomas-JACQUOT** [comment]
This problem is solved thanks to the PR above, We can close this issue now.
