### ISSUE TITLE
PyGRB's tables of injections seem to be broken under Numpy >2

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4968]
Tables of injections do not show up in PyGRB runs done with Numpy >2. Compare for example [this page](https://ldas-jobs.ligo.caltech.edu/~thomas.jacquot/LVC/pygrb_test2_novetoes/3._injections/3.01_NSBH/) (from a run on Numpy 1.x) with [this one](https://ldas-jobs.ligo.caltech.edu/~thomas.jacquot/LVC/pygrb_test2_novetoes_no_cal_errors/3._injections/3.01_NSBH/) (from a run on Numpy >2). Scroll to the bottom; the second link has no tables in the "missed found injections" and "quiet found injections" sections.

The HTML files for the tables are present in both versions. However, inspecting the HTML source of both versions, there is a difference in one line of JavaScript. The working version has
```
        data.addRows([[38.32068336227897, 79.31437109418879, 150.04242045953802, …
```
while the broken version has
```
        data.addRows([[np.float64(38.32068336227897), np.float64(79.3143710941888), np.float64(150.04242045953802), …
```
So this looks like some data type problem, presumably related to the type promotion changes in Numpy 2.

**Comment by ahnitz** [comment]
Maybe it's just a difference in how the representation looks? It looks like the number itself is the same down to the last digit, so maybe it's that we are effectively making a string with 

```
repr(number) 
```

**Comment by titodalcanton** [comment]
I bet the problem is in these lines of `pycbc.results.html_table()`:
```python
    data = []
    for item in zip(*columns):
        data.append(list(item))
```

**Comment by titodalcanton** [comment]
So in Numpy 1.24.3 I get this:
```
>>> import numpy as np
>>> x = np.float64(12)
>>> x
12.0
>>> str(x)
'12.0'
>>> repr(x)
'12.0'
```
while on Numpy 2.1.3 I get this:
```
>>> import numpy as np
>>> x = np.float64(12)
>>> x
np.float64(12.0)
>>> str(x)
'12.0'
>>> repr(x)
'np.float64(12.0)'
```
So it looks like we need an explicit `str()` on each item before passing it to the template for rendering.
