### ISSUE TITLE
Error for plot_sensitivity when running the test-workflow with v1.3.7 executables on OSG

### ISSUE THREAD

**Issue by soumide1102** [gwastro/pycbc#767]
When running the test workflow the job `plot_sensitivity-MCHIRP_BINSVT_BNS01_INJ_INJ-H1L1_ID133_ID0000646` failed 
and gives the error : `ValueError: Data has no positive values, and therefore can not be log-scaled.`

The error traces back to line 240 of the code pycbc_page_sensitivity. 

Link to the failed job details on the pegasus-dashboard is https://sugar-dev2.phy.syr.edu/pegasus/u/soumi.de/r/61/w/2/j/86/ji/1036

**Comment by duncan-brown** [comment]
Closing, as it's a 1.3.7 issue. Please re-open if it happens with 1.5.x.

**Comment by stevereyes01** [comment]
Issue persists in pycbc master (as of August 23rd). I think we can fix this with a case where if it doesn't find any positive values it doesn't try to plot in log scale.

**Comment by stevereyes01** [comment]
This error seems to be GPS dependent, as I just had a workflow pass through.

https://sugar-jobs.phy.syr.edu/~steven.reyes/O1/testWorkflow/SugarAug24/TestWorkflow1/

I'll have to do more investigating to figure out what's bugging out in the small test workflows we were running before.

**Comment by duncan-brown** [comment]
@stevereyes01 please can you take a look at this?

**Comment by stevereyes01** [comment]
Yeah, I haven't noticed this bug creep back in in any of the latest runs, but what I should do is run a small test workflow over the GPS times.

**Comment by duncan-brown** [comment]
Removing the milestone until this is investigated.
