### ISSUE TITLE
Give pycbc_generate_hwinj{,_from_xml} ability to write h(t) frame files for AdVirgo

### ISSUE THREAD

**Issue by johnveitch** [gwastro/pycbc#816]
Advanced Virgo will read h(t) frame files for its HW injections, similar to initial Virgo. The pycbc_generate_hwinj scripts currently produce text files for H and L. This will need to be extended to write h(t) frames for V as well.

**Comment by ahnitz** [comment]
Chris, is this now supported? If so please close.

**Comment by cmbiwer** [comment]
Hi Alex, not supported yet... I think this is much more than a code change, there's some managerial things that need to be decided about how data is stored.

**Comment by duncan-brown** [comment]
@johnveitch please can you find someone from the CBC group on the Virgo side to take this on?
